### ISSUE TITLE
Accessor alignment should refer to the type, not only the componentType

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Validator#10]
The [alignment constraints for accessors](https://github.com/lexaknyazev/glTF/tree/1.0.1/specification#bufferview-and-accessor-byte-alignment) say

> The offset of an accessor into a bufferView (i.e., accessor.byteOffset) and the offset of an accessor into a buffer (i.e., accessor.byteOffset + bufferView.byteOffset) must be a multiple of the size of the accessor's attribute type.

where "attribute type" is defined to be the size of the *full* type, e.g. for a 3D float vector, it's 3*4 bytes.

The error message that I just received was

    "type": "ACCESSOR_TOTAL_MULTIPLE_COMPONENT_TYPE",
    "path": "/accessors/positionsAccessor/byteOffset",
    "message": "Accessor's total byteOffset `6` isn't a multiple of a componentType length `4`."

indicating that it only checks for the `componentType`. 

(Maybe this could also be made clearer by rephrasing the statement about the "data type" in https://github.com/KhronosGroup/glTF/blob/master/specification/1.0/schema/accessor.schema.json#L19 , e.g. by replacing it with "attribute size" or any other more detailed description. I'll consider a PR for that, if this is OK)

--- 

Context: While validating the tutorial sample models for https://github.com/KhronosGroup/glTF-Sample-Models/issues/16 , I noticed that some of them do not obey the constraints. I'm currently fixing them.

**Comment by lexaknyazev** [comment]
After some investigation, I think that we should refine spec wording here, not validation rule.

The reasoning behind that constraint is that JS runtime could create multiple "views" from the same ArrayBuffer without copying data if a new offset is aligned with new array type. Specifics of that process are described in [ECMA-262, 22.2.1.5](http://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%-buffer-byteoffset-length). 

**`Triangle.gltf` with positions starting at 6:**
```javascript
var ubyteArray = new Uint8Array([0x00, 0x00, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x00]);
var indices = new Uint16Array(ubyteArray.buffer, 0, 3); // [0, 1, 2]
var positions = new Float32Array(ubyteArray.buffer, 6) // RangeError: start offset of Float32Array should be a multiple of 4
```

**`Triangle.gltf` with positions starting at 8:**
```javascript
var ubyteArray = new Uint8Array([0x00, 0x00, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x00]);
var indices = new Uint16Array(ubyteArray.buffer, 0, 3); // [0, 1, 2]
var positions = new Float32Array(ubyteArray.buffer, 8) // [0, 0, 0, 1, 0, 0, 0, 1, 0]
```

So, there's no need to force 12-byte alignment in this case.

**Comment by javagl** [comment]
I also thought this when I read the related issue https://github.com/KhronosGroup/glTF/issues/167 (originally by @pjcozzi). But then I thought that there *might* be a deeper reason behind this, which I'm not aware of.

Particularly, I wondered whether there may be cases where `vec3` elements...
- *have to be* aligned to 3*4 bytes for certain (OpenGL-related) functions
- *should be* aligned to 3*4 bytes, e.g. for performance reasons 

I did not find a source that said that the elements *have to be* aligned. (In the end, the actual buffer data is allocated by GL, and it will take care of the alignment requirements. This issue is just about the host data). There are some vague statements that indicate that the elements *should be* aligned to achieve a higher transfer performance, but nothing that seems to be profoundly based on the specs or profiling results...

In any case, I want to emphasize this, even if it may be obvious:

**This is a one-way road!**

Right now, the alignment constraint is `componentSize * componentCount`. When we relax it to only `componentSize`, then we can **never** take this back. (This *might* already be a reason to be conservative here. For example: Does anybody know whether Vulkan imposes additional constraints or preferences regarding the alignment...?)

**Comment by lexaknyazev** [comment]
> Right now, the alignment constraint is `componentSize * componentCount`

It's unclear for me why is that. https://github.com/KhronosGroup/glTF/issues/167 refers to JS Typed Array alignments, however I see that spec implies `componentCount`.

Btw, collada2gltf [uses only 4-byte boundaries](https://github.com/KhronosGroup/COLLADA2GLTF/blob/master/GLTF/GLTFAsset.cpp#L1043-L1052).

---

Performance-wise general advice is to use 32-bit boundaries for attributes to avoid extra data copying. 
So I think spec should demand:
- Component type alignment of all accessors and
- 4-byte alignment of attribute accessors (new constraint, affects `byteOffset` and `byteStride`).

---

**[OpenGL wiki](https://www.khronos.org/opengl/wiki/Vertex_Specification_Best_Practices#Attribute_sizes)**
> The alignment of any attribute's data should be no less than 4 bytes. So if you have a `vec3` of `GLushort`​s, you can't use that 4th component for a new attribute (such as a `vec2` of `GLbyte`​s). If you want to pack something into that instead of having useless padding, you need to make it a `vec4` of `GLushort​`s.

**Vulkan's [Vertex Input Description](https://vulkan.lunarg.com/doc/view/1.0.37.0/windows/vkspec.chunked/ch20s02.html)**
> If `format` is a packed format, `attribAddress` must be a multiple of the size in bytes of the whole attribute data type as described in [Packed Formats](https://vulkan.lunarg.com/doc/view/1.0.37.0/windows/vkspec.chunked/ch31s03.html#features-formats-packed). Otherwise, `attribAddress` must be a multiple of the size in bytes of the component type indicated by `format` (see [Formats](https://vulkan.lunarg.com/doc/view/1.0.37.0/windows/vkspec.chunked/ch31s03.html)). 

**Apple's [OpenGL ES Programming Guide](https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html#//apple_ref/doc/uid/TP40008793-CH107-SW7)**
> When you are designing your vertex structure, align the beginning of each attribute to an offset that is either a multiple of its component size or 4 bytes, whichever is larger.

**Apple's Metal [MTLVertexAttributeDescriptor.offset](https://developer.apple.com/reference/metal/mtlvertexattributedescriptor/1515785-offset)**
> The `offset` value must be a multiple of 4 bytes.

Layout examples in [Vertex Descriptor for Data Organization](https://developer.apple.com/library/content/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/Render-Ctx/Render-Ctx.html#//apple_ref/doc/uid/TP40014221-CH7-SW44)

**Comment by lexaknyazev** [comment]
What's more important, that aligning several attributes of different lengths will result in unusually big gaps in vertex data:
Let's say we've got two attributes, both of `GL_FLOAT`: `vec3 att1` and `vec4 att2`.
To have them in one buffer while satisfying `componentSize * componentCount` alignment, we have two options:
- `12 bytes of att1 + 4 bytes gap + 16 bytes of att2` or
- `16 bytes of att2 + 8 bytes gap + 12 bytes of att1`.

This doesn't look quite right for me and I don't know any particular reasoning for such layout.

**Comment by javagl** [comment]
(BTW: To avoid misunderstandings: With "alignment" we here refer to the "total offset of an accessor into its bufferView and its buffer")

Regarding the last point, about the "gaps" in the data: I assume that this particularly refers to *interleaved* data. For the worst case of interleaved attributes consisting of 1. `float` `mat4` elements (16*4 bytes) and 2. `float` `scalar` elements, the wasted space would otherwise be ridiculous (whereas for non-interleaved data, each gap would appear only once, which would not be an issue, I guess). 

Until now, I also think that the `componentSize` alignment should be sufficient. But to be sure, will have to read a bit more about this. I had already seen some of your links, but not all of them, and when it comes to detals, also regardign interleaved data, it's definitely necessary to read them more thoroughly.

(Unless someone who already knows better can already make a profound decision here)

**Comment by pjcozzi** [comment]
Whatever you two decide is OK with me, but please create an issue in the glTF repo and continue this discussion there (and link to this) so we have the archive in one place.

**Comment by lexaknyazev** [comment]
>  With "alignment" we here refer to the "total offset of an accessor into its bufferView and its buffer"

This two-level alignment is definitely JS Typed Array related (to reuse ArrayBuffer as shown above). It provides efficient way to access buffer data values from JS (however it's really needed only for skinning's IBM data).

**Comment by javagl** [comment]
As per request, I opened the issue in the glTF repo.

(Depending on the decision there, this issue here might become obsolete, but let's see what the outcome is)

**Comment by javagl** [comment]
So this can probably be closed as of https://github.com/KhronosGroup/glTF/issues/802#issuecomment-274294301
