### ISSUE TITLE
Clarify "Unsupported Extension" means the validator doesn't support the extension

### ISSUE THREAD

**Issue by sbtron** [KhronosGroup/glTF-Validator#101]
Since the Babylon.js Sandbox and three.js gltf-viewer both provide validation results along with the viewer some developers are getting confused that it might be the viewers that don't support the extension. 

It might be useful to clarify in the message that "Unsupported Extension" simply means validator does not support it and therefore cannot fully validate the file.
Maybe something like: 
"message": "Cannot validate extension as it is not supported by validator: 'KHR_lights_punctual'.",

Also is there a list of extensions supported by the validator somewhere? Couldn't seem to find it.

**Comment by lexaknyazev** [comment]
I'm fine with adjusting the message. The full list of supported extensions isn't present anywhere. 
We can easily include it with:
- a validation report somewhere near validator's version;
- README.md;
- command-line usage info.

**Comment by lexaknyazev** [comment]
We can also separate completely unknown extensions from those that validator doesn't support.
