### ISSUE TITLE
collada2GLTF and dae with linesegments inside

### ISSUE THREAD

**Issue by ua4192** [KhronosGroup/glTF-Validator#106]
Hi.

I am facing problems with the collada2gltf binary and collada files with LineSegments inside.

It happens with all versions of the convertor.

When to pass a input dae file with LineSegments inside the convertor doesn't generate anything.

Is there any fix for this?

Many thanks in advanced.

**Comment by lexaknyazev** [comment]
Hi. This is a glTF-Validator repo. Please use [COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF/issues) repo for converter's issues.
