### ISSUE TITLE
Integer check on accessor.count

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Validator#109]
Based on this file : https://github.com/KhronosGroup/glTF-Blender-IO/files/2685805/toy_car_gltf.tar.gz

Online validator says that gltf is valid, but there is a accessor.count of 708.0.
Spec says that count must be integer, but 708.0 is not an integer

**Comment by lexaknyazev** [comment]
Command-line version doesn't use JavaScript runtime and marks accessor.count of 708.0 as invalid.

**Comment by emackey** [comment]
Looks like VSCode's copy of the validator catches this.  👍

**Comment by lexaknyazev** [comment]
In VSCode, JSON schemas catch this, not the validator.

**Comment by emackey** [comment]
I don't think there's anything to do here.  JSON.parse isn't going to detect the .0, but there are other ways to detect it (use the commandline version, for example).

Let me know if this should be reopened for any reason.
