### ISSUE TITLE
accessor bounds fail with normalized accessor

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF-Validator#112]
I am generating a 3D model with a Vector4 x UnsignedByte x Normalized accessor, when checking it against the online validator, it reports this error:

```json
"messages": [
            {
                "code": "ARRAY_TYPE_MISMATCH",
                "message": "Type mismatch. Array element 0.49803921580314636 is not a 'integer'.",
                "severity": 0,
                "pointer": "/accessors/3/min"
            },
            {
                "code": "ARRAY_TYPE_MISMATCH",
                "message": "Type mismatch. Array element 0.49803921580314636 is not a 'integer'.",
                "severity": 0,
                "pointer": "/accessors/3/max"
            }
        ],
```

The actual value being stored in the buffer is 127.
After normalization 127/255 = 0.49803921  so the bound values I am calculating are fine.

So, what's the deal? should I store the unnormalized bounds? or it's the validator failing?

**Comment by lexaknyazev** [comment]
From the spec property reference (`accessor.max`):
> `normalized` property has no effect on array values: they always correspond to the actual values stored in the buffer.

**Comment by vpenades** [comment]
@lexaknyazev ouch! I thought the bounds represented the actual exposed values, not the stored ones.
