### ISSUE TITLE
Asset receive error in Validator web UI but not in Node package

### ISSUE THREAD

**Issue by jclarkk** [KhronosGroup/glTF-Validator#115]
Attached the problematic GLTF asset.
[bad.zip](https://github.com/KhronosGroup/glTF-Validator/files/3008050/bad.zip)

I don't get any errors when running via nodejs but in the Web UI:

https://github.khronos.org/glTF-Validator/

I get an error.

**Comment by lexaknyazev** [comment]
The actual binary payload size (`Product.bin`) is less than its size declared in JSON. 

The validator can validate only those resources that are provided to it. So you will see this error in WebUI only when dropping both `Product.gltf` and `Product.bin` files.

To get the same validation output in nodejs environment, the validator library should be used like shown in the full example [here](https://github.com/KhronosGroup/glTF-Validator/tree/master/node#full-usage).

**Comment by jclarkk** [comment]
Ah great, sorry for missing that!

Thanks
