### ISSUE TITLE
Animation sampler validation

### ISSUE THREAD

**Issue by shrinktofit** [KhronosGroup/glTF-Validator#116]
* Validity of input/output element count of animation sampler.

In specification:
> The number output of elements must equal the number of input elements. (for LINEAR and STEP)
> For each input element, the output stores three elements, an in-tangent, a spline vertex, and an out-tangent. There must be at least two keyframes when using this interpolation. (for CUBICSPLINE)

Related issue:
https://github.com/KhronosGroup/glTF-Blender-IO/issues/465

**Comment by lexaknyazev** [comment]
The validator checks for these constraints. Is there any specific example that is not covered?

**Comment by shrinktofit** [comment]
This might be my mistake. I will check it by myself.
