### ISSUE TITLE
No message for unused texcoords if there is no material

### ISSUE THREAD

**Issue by stevk** [KhronosGroup/glTF-Validator#117]
A material must be present before the validator will message that there are unused texcoords. Is this intentional?

[Texcoords.zip](https://github.com/KhronosGroup/glTF-Validator/files/3307422/Texcoords.zip)

**Comment by lexaknyazev** [comment]
Not a strong opinion, but it was intentional at the time of implementing that check. 
Would you prefer that all UVs on a material-less mesh be marked as unused?

**Comment by stevk** [comment]
I think we would prefer that. We have made efforts in the gltf-asset-generator to avoid adding UVs if they aren't used, material present or otherwise, and were suprised that the validator didn't catch the unused UVs in this scenario. 

@bghgary, would you like to comment?

**Comment by bghgary** [comment]
I prefer the same behavior irregardless of whether a materials is present or not.

@lexaknyazev Why is this intentional?
