### ISSUE TITLE
Should all buffers with empty uri be treated as GLB buffers?

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glTF-Validator#121]
I'm not sure if this is a validator issue or I'm reading the spec wrong.

Following https://github.com/KhronosGroup/glTF/issues/1680, I started to implement support for producing files alongside what was suggested in the issue - emit "dummy" buffer with no data, with the MESHOPT_compression extension overriding that.

I'm encountering an issue where the validator thinks *both* buffers are stored in the .glb file with the following header:

```
"buffers":[{"byteLength":394128},{"byteLength":1166032}],
```

are stored in .glb file:

```
        "resources": [
            {
                "pointer": "/buffers/0",
                "mimeType": "application/gltf-buffer",
                "storage": "glb",
                "byteLength": 394128
            },
            {
                "pointer": "/buffers/1",
                "mimeType": "application/gltf-buffer",
                "storage": "glb",
                "byteLength": 394128
            }
        ],
```

and getting the following errors as a result:

```
            {
                "code": "BUFFER_NON_FIRST_GLB",
                "message": "Buffer referring to GLB binary chunk must be the first.",
                "severity": 0,
                "pointer": "/buffers/1"
            },
            {
                "code": "BUFFER_EXTERNAL_BYTELENGTH_MISMATCH",
                "message": "Actual data length 394128 is less than the declared buffer byteLength 1166032.",
                "severity": 0,
                "pointer": "/buffers/1"
            }
```

Is this expected behavior, or is the validator not doing the right thing here?

Attaching the example file fwiw:
[BrainStem.glb.zip](https://github.com/KhronosGroup/glTF-Validator/files/3707143/BrainStem.glb.zip)

**Comment by zeux** [comment]
Worth noting is that the .gltf file output works as expected:

```
        "resources": [
            {
                "pointer": "/buffers/0",
                "mimeType": "application/gltf-buffer",
                "storage": "external",
                "uri": "BrainStem.bin"
            },
            {
                "pointer": "/buffers/1",
                "mimeType": "application/gltf-buffer",
                "storage": null
            }
        ],
```

**Comment by lexaknyazev** [comment]
That's certainly a validation issue.

GLB format says that the buffer object with index 0 points to a GLB-stored binary part and should not have an URI. Looks like the validator treats _all_ buffers without URI as pointing to GLB-stored chunk when an asset uses GLB format.
