### ISSUE TITLE
Validation failed:  NoSuchMethodError: method not found: 'a' on null

### ISSUE THREAD

**Issue by fiesh** [KhronosGroup/glTF-Validator#125]
The attached file leads to the error message above in the `npm` version of the validator.  The browser based validator gets stuck in "Validating...".

[bg1.zip](https://github.com/KhronosGroup/glTF-Validator/files/4039330/bg1.zip)

**Comment by emackey** [comment]
Thanks for the report @fiesh

**Comment by fiesh** [comment]
> Thanks for the report @fiesh

You're welcome!  Thanks for the super quick fix!
