### ISSUE TITLE
Windows command-line build output

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#126]
I'm trying the 2.0.0-dev.3.0 Win64 build (both my own local build, and the one from the [releases page](https://github.com/KhronosGroup/glTF-Validator/releases).

I placed it in the glTF-Sample-Models folder (mimicing what Travis CI does in Linux), and ran it like this in both Git Bash and in Windows Powershell:

```
./gltf_validator -r -a ./2.0/AlphaBlendModeTest/
```

I also tried this in Powershell:

```
.\gltf_validator.exe -r -a .\2.0\AlphaBlendModeTest\
```

Windows accepts both directions of slashes.  In all cases, the validator recursively looked for glTFs in the named folder, correctly printed (to the shell) the validation summary (just like in Travis CI), and made empty files named like this:

```
AlphaBlendModeTest.gltf.report.json
```

The problem is, these json files are all zero bytes long.  They don't contain a validation report.

This problem appears isolated to the Windows command-line version only.

**Comment by lexaknyazev** [comment]
While I do not see this behavior on my machine (reports are written as expected), I have an idea what's going on there.

Please try `flush-io` branch.

**Comment by emackey** [comment]
Yes, `flush-io` fixes the issue for me.
