### ISSUE TITLE
Camera perspective yfov has no upper limit.

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF-Validator#140]
The test/base/data/camera/extra_type.gltf defines camera perspective YFOV with value 10.

The official specification states that the value must be over 0, and although it does not explicitly state the upper limit, it states that the value is defined as radians, which sets an implicit upper limit.

Also, the spec says the value must be used in formulas using the form `Tan(0.5*yfov)`  which implicitly sets the upper limit _below π_.

I guess the spec does not define the upper limit because it's a non rational number?  but math libraries certainly define it...

So I guess at the very least the gltf_validator should take this into account.

**Comment by lexaknyazev** [comment]
Opened a spec issue. Will add validation warning anyway.

**Comment by lexaknyazev** [comment]
Fixed in `2.0.0-dev.3.3`.
