### ISSUE TITLE
No explicit warning when using unlit and pbrSpecularGlossiness

### ISSUE THREAD

**Issue by UX3D-haertl** [KhronosGroup/glTF-Validator#145]
Currently, there is only a general warning if multiple extensions are used in one object.
But in the unlit spec this is stated:

> **Implementation Note:** When `KHR_materials_unlit` is included with another
> extension specifying a shading model on the same material, the result is
> undefined.

Therefore, if unlit and pbrSpecularGlossiness exist in a material a more explicit warning about the undefined state might be needed.

**Comment by emackey** [comment]
Yes.  Almost all of the upcoming "PBR Next" set of extensions are expected to play well with each other, and specifically exclude both `KHR_materials_unlit` and `KHR_materials_pbrSpecularGLossiness` from being in the same material.

**Comment by lexaknyazev** [comment]
Fixed in `2.0.0-dev.3.3`.
