### ISSUE TITLE
Reporting KHR_materials_variants schema peculiarities

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Validator#149]
The schemas for `KHR_materials_variants` define `gltf.extensions['KHR_materials_variants'].variants[].extras` and `gltf.meshes[].primitives[].extensions['KHR_materials_variants'].mappings[].extras` as JSON objects, while the base spec allows `extras` to have any type.

Assuming that it was the intentional design decision, how should the validator report wrong types for these properties?
We already have an info-level `NON_OBJECT_EXTRAS` validation issue that says "Prefer JSON Objects for extras." that is applied to all other `extras`.

Possible options:
- raise the severity of `NON_OBJECT_EXTRAS` to Error when encountered in those two places;
- report `TYPE_MISMATCH` error-level issue;
- define a new issue code and a message for this extension.

/cc @donmccurdy @emackey

**Comment by emackey** [comment]
I'd be concerned about using the same message code at different severity levels, because we allow users to configure severity per individual message code.  I don't think the configuration options would work well if the same code was intended to be used at different severities.

So, if `TYPE_MISMATCH` is applicable, that would get my vote.

**Comment by lexaknyazev** [comment]
Should we double-check the requirement with the extension's authors? Reporting `TYPE_MISMATCH` is straightforward.

**Comment by lexaknyazev** [comment]
Specifically, do they want all other possible `extras` slots in the extension to be restricted to JSON objects?

**Comment by emackey** [comment]
@sleroux @pushmatrix Do you guys know if there's a specific reason why `extras` is different in the `KHR_materials_variants` extension compared to the rest of glTF?  Or is that an inconsistency we should remove?

FWIW, this extension treats `extras` a little more strictly than the rest of glTF, which might be considered a good thing.  Some future version of glTF might tighten it to be more like what this extension does.  Maybe we should leave it this way, in spite of the inconsistency.

**Comment by lexaknyazev** [comment]
The two `extras` fields from this extension that follow the base spec (i.e. can be of any type) are
- `gltf.extensions['KHR_materials_variants'].extras`
- `gltf.meshes[].primitives[].extensions['KHR_materials_variants'].extras`

**Comment by emackey** [comment]
Given the lack of reply, I don't think people much care about non-object `extras`.  Let's flag `TYPE_MISMATCH` for the ones that happen to have more strict type safety in this extension.

**Comment by lexaknyazev** [comment]
> Let's flag `TYPE_MISMATCH` for the ones that happen to have more strict type safety in this extension.

I'm still hoping that the schema could be relaxed there to avoid special-casing `extras` just for this extension.

**Comment by sleroux** [comment]
Sorry for the delayed response on this. It wasn't the intention to make the `extras` different from the rest of glTF so `TYPE_MISMATCH` would be good :+1:

**Comment by emackey** [comment]
Thanks @sleroux.  Rather than add `TYPE_MISMATCH`, it looks like the consensus here may be to bug-fix the variants schema itself, in https://github.com/KhronosGroup/glTF/pull/1922.

**Comment by lexaknyazev** [comment]
@sleroux 
Well...

If the intention is to align the extension with the rest of the spec, then `extras` should be of any type and there would be no `TYPE_MISMATCH` error there.

If the intention is to have `TYPE_MISMATCH` on the two `extras` slots of the extension, it would be different from the rest of the glTF.

**Comment by sleroux** [comment]
> If the intention is to align the extension with the rest of the spec, then extras should be of any type and there would be no TYPE_MISMATCH error there.

Sorry I misread. Yes this I'm in favor of moving forward with Ed's PR to turn the extras type to any which would avoid any type issues. Sure we lose the typechecking on it but it was never the intention to constrain extras to object and make it different than other extras - this was an error in the schema.

**Comment by emackey** [comment]
The schema is fixed now, merged in https://github.com/KhronosGroup/glTF/pull/1922.

**Comment by lexaknyazev** [comment]
No longer relevant as the schemas were fixed.
