### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Validator#15]
Creating an issue from discussion elsewhere, can we publish transpiled JS for glTF validator to npm, so that pure-JS projects can depend on it?

**Comment by lexaknyazev** [comment]
That's my highest priority atm.

**Comment by lexaknyazev** [comment]
See #23.

**Comment by emackey** [comment]
https://www.npmjs.com/package/gltf-validator

**Comment by emackey** [comment]
@lexaknyazev Now that this package exists, would it be possible to add a new `pub run grinder npm-publish` or similar command?  Such a command could just be a shortcut to execute these shell commands:

```
cd build/npm
npm publish
cd ../..
```

**Comment by lexaknyazev** [comment]
@emackey 
Why the third one is needed?

**Comment by emackey** [comment]
Not needed, just tidying up.  Seems wrong to leave the user in a different place from where they started, particularly if they plan to run more commands.

**Comment by lexaknyazev** [comment]
Does `npm publish` require user interaction?

**Comment by emackey** [comment]
> Does `npm publish` require user interaction?

No.  If the user is not logged in, it will print an error message telling the user to run `npm login`, and if they are not authorized it will ask them to log in again as a different user.  It will not ask for any information interactively, as everything it needs is in `package.json`.

**Comment by lexaknyazev** [comment]
@emackey See #25.

**Comment by lexaknyazev** [comment]
@donmccurdy @emackey 
OK to close this?

**Comment by emackey** [comment]
Yep.

**Comment by donmccurdy** [comment]
Yes, thanks!
