### ISSUE TITLE
Spurious "MESH_PRIMITIVE_ACCESSOR_WITHOUT_BYTESTRIDE"?

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Validator#16]
Take [Triangle.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/blob/c89c1709fbfd67a11aa7e540ab4ecb795763b627/2.0/Triangle/glTF-Embedded/Triangle.gltf) and duplicate the mesh (producing [this](https://gist.github.com/scurest/dbf984eb83ec0c17ef152bb9d7324b26)), then run it through the online validator. You get an error with the message

> `bufferView.byteStride` must be defined when two or more accessors use the same buffer view.

But there are not two or more accessors which use the same buffer view.

**Comment by lexaknyazev** [comment]
Fixed.
