### ISSUE TITLE
Reference to missing sourcemap in NPM package

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Validator#160]
The code published to NPM contains this line...

```js
//# sourceMappingURL=gltf_validator.dart.js.map
```

https://unpkg.com/gltf-validator@2.0.0-dev.3.3/gltf_validator.dart.js

... which will cause tools to look for a sourcemap at the given URL. That file doesn't exist, or doesn't get published to NPM, so I see the following errors when building an app using `gltf-validator` in Parcel:

> ⚠️  Could not load existing sourcemap of "node_modules/gltf-validator/gltf_validator.dart.js".

Things still work, it's just a warning. But I think we should (a) publish the sourcemaps to NPM, or (b) remove the link to the sourcemaps. I don't think I have a preference between the two, though I'd be curious how large the sourcemap file is.

**Comment by emackey** [comment]
Looks like the sourcemap link got removed from 2.0.0-dev.3.4.
