### ISSUE TITLE
Malware detected in compiled CLI tool

### ISSUE THREAD

**Issue by akiesskp** [KhronosGroup/glTF-Validator#162]
I compiled the CLI tool today, and in the process of copying it to another machine discovered it is flagged as containing malware. 

GoogleDrive/Gmail will not allow downloading the exe due to detected malware, and both VirusTotal and MetaDefender have flagged it as containing trojans. 

Are these known issues? 
https://www.virustotal.com/gui/file/c18eaf796e07c4789f45bb3f4601d1ff8b2b35d849ce722995c42dd14134ba8d/detection
https://metadefender.opswat.com/results/file/31c4028bc46766d02bfb19607a6bc276/hash/multiscan?lang=en

I have confirmed that compiling the exe on a different, isolated machine produced the same thing.

**Comment by lexaknyazev** [comment]
Yeah, I see similar results with 2.12.4. Compiling with beta SDK (2.13) doesn't trigger those detections, though.

**Comment by akiesskp** [comment]
I can try that, thanks.

**Comment by lexaknyazev** [comment]
The issue seems to be resolved with SDK 2.13.
