### ISSUE TITLE
Matrix must be decomposable to TRS issue

### ISSUE THREAD

**Issue by vaibhav-bhandari** [KhronosGroup/glTF-Validator#164]
I am trying to extract geometry information from one of the modelling software and create GLTF.
While doing so I encountered one transformation matrix which is as below 
![image](https://user-images.githubusercontent.com/43267365/119628157-770a4e00-be2a-11eb-9392-3523b779f907.png)
The issue is visual output is perfect but it fails for GLTF validation through GLTF validator (https://github.khronos.org/glTF-Validator)
As the error message displays : "Matrix must be decomposable to TRS." 
So I used the reference from this to decompose the matrix into TRS form : https://github.com/KhronosGroup/glTF-Validator/issues/33
Decomposed TRS also returns the error so any input on this would be helpful. 
Refer attached GLB file for the same

[wick_14.zip](https://github.com/KhronosGroup/glTF-Validator/files/6545251/wick_14.zip)

**Comment by lexaknyazev** [comment]
> Decomposed TRS also returns the error

Decomposing TRS matrix would mean replacing the `node.matrix` property with equivalent `node.scale`, `node.rotation`, and `node.translation` values. What error is displayed in this case?

**Comment by vaibhav-bhandari** [comment]
> > Decomposed TRS also returns the error
> 
> Decomposing TRS matrix would mean replacing the `node.matrix` property with equivalent `node.scale`, `node.rotation`, and `node.translation` values. What error is displayed in this case?

![image](https://user-images.githubusercontent.com/43267365/119638892-b9388d00-be34-11eb-9037-ed26069b0fa0.png)

**Comment by lexaknyazev** [comment]
Rotation vector is a normalized quaternion, i.e. it must have unit length and each component must be within `[-1 ... 1]` range.
