### ISSUE TITLE
NODE_EMPTY minor inconsistency?

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#176]
This is just a little wrinkle I noticed, not causing any problems, but:

The `NODE_EMPTY` info message gets turned off for any nodes that contain the `extras` field, but does not turn itself off when `extensions` are present.  Perhaps the presence of any extensions on a node should suppress this message as well?

**Comment by lexaknyazev** [comment]
The issue is turned off when the `extensions` object is not empty. However, unknown extensions are not considered. I think the latter part is a bug.

**Comment by emackey** [comment]
Yes, I would consider `extras` and unknown vendor extensions to be on the same footing here.

**Comment by lexaknyazev** [comment]
Fixed in #179.
