### ISSUE TITLE
Check "All primitives MUST have the same number of morph targets"

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Validator#182]
The spec says

> All primitives **MUST** have the same number of morph targets in the same order.

I believe that means this should be invalid

```json
"primitives" : [
  {
    "attributes" : {
      "POSITION" : 0
    },
    "indices" : 1,
    "material" : 0
  },
  {
    "attributes" : {
      "POSITION" : 3
    },
    "indices" : 4,
    "material" : 1,
    "targets" : [
      {
        "POSITION" : 5
      }
    ]
  }
],
```

[Example file](https://github.com/KhronosGroup/glTF-Validator/files/8596714/MorphTargetExample.zip)

It passes validation when using https://github.khronos.org/glTF-Validator/ though.

**Comment by lexaknyazev** [comment]
Good catch. I think we need to clarify the spec first. Opened https://github.com/KhronosGroup/glTF/issues/2154.

**Comment by scurest** [comment]
Actually I realized this is already checked, but it depends on the primitive order; it only starts checking the lengths after the first primitive with a `targets`. So swapping those primitives above would trigger the error. That's definitely wrong right?

**Comment by lexaknyazev** [comment]
> That's definitely wrong (primitive order does not affect validity) right?

I agree that the validation bug is there but the correct report (i.e., whether the snippet above is valid or not) would depend on the clarified spec language.

**Comment by lexaknyazev** [comment]
The new version has been released.
