### ISSUE TITLE
Volume thickness vs. doubleSided

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#186]
A suggestion for an additional validation of `KHR_materials_volume`:

When `thicknessFactor` is nonzero, the polygon mesh is [expected to be closed, manifold volume](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_volume#extending-materials) of material.  Generally this implies that `doubleSided` should be `false` for meshes using such a material.

It may be too expensive to add a full manifold mesh test in here just for this, but issuing a warning on the use of `doubleSided` might be a good idea.

**Comment by lexaknyazev** [comment]
Implemented in #185. Please take a look.
