### ISSUE TITLE
Unusual error and warnings

### ISSUE THREAD

**Issue by MoSaeedNahlous** [KhronosGroup/glTF-Validator#187]
recently i was uploading a glb file to the editor on Model-viewer and a "Validation Error" came up with 8 lines of errors like this one:

ANIMATION_SAMPLER_ACCESSOR_WITH_BYTESTRIDE | bufferView.byteStride must not be defined for buffer views used by animation sampler accessors. | /animations/0/samplers/0/output

and another warnings messeges like:

UNUSED_OBJECT | This object may be unused. | /meshes/0/primitives/0/attributes/TEXCOORD_0

and this:

NODE_EMPTY | Empty node encountered. | /nodes/375

any idea on how to fix these problems?

**Comment by lexaknyazev** [comment]
- `ANIMATION_SAMPLER_ACCESSOR_WITH_BYTESTRIDE` is an error that should be reported to the model's author and/or the tool that was used to create it.
 - `UNUSED_OBJECT` and `NODE_EMPTY` warnings are harmless. They usually mean that the model has suboptimal internal structure.
