### ISSUE TITLE
node_weights_override.gltf  not reporting bufferview not defined?

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF-Validator#189]
I've noticed that files like `node_weights_override.gltf` and others, define accesors that report having vertices (count not zero), but don't point to a bufferview.

Why this is not giving any error in glTF validator?

I am aware that in these files, the accessors are being used by meshes that don't contribute to a scene, so any invalid configuration in them would be transparent.... but if that's the case, what's the point on validating the other stuff of the mesh?

Specifically, in `node_weights_override.gltf`,  if the Mesh and Node are not attached to a scene, why the weights override is being considered, but the missing bufferview is not being considered?

**Comment by lexaknyazev** [comment]
That may be a bug, I'll investigate.

**Comment by vpenades** [comment]
Hmm... I understand that BufferView is not required, `as long as the data is provided by other means`, as you say.

So talking broadly, the error would be "the accessor can't access the data it represents by any means"

I understand it makes writing test cases easier... but given how strict we are in other aspects of the schema, I see this as a bit of cheating.

**Comment by lexaknyazev** [comment]
> _as long as the data is provided by other means_

There's no such requirement in the spec, so data remains undefined.

**Comment by vpenades** [comment]
> There's no such requirement in the spec, so data remains undefined.

Okey, so, if I take one of these examples (provided the node and the mesh are instanced in a scene) and I try to load the model in a game engine or something.... which is the expected behavior?  crash on load?, silently skip the mesh?  I think this should be clarified
