### ISSUE TITLE
invalid error: URI_GLB

### ISSUE THREAD

**Issue by malytomas** [KhronosGroup/glTF-Validator#195]
According to specification: https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#glb-file-format-specification-general it is allowed to have references for external textures. However, the validator issues an error stating that it is not allowed.

![gltf-validation](https://user-images.githubusercontent.com/18198295/184857154-0bf4a225-7f8d-4b3f-82ce-4fefedd7e002.png)

Testing file:

[meshes.zip](https://github.com/KhronosGroup/glTF-Validator/files/9349840/meshes.zip)

**Comment by lexaknyazev** [comment]
`URI_GLB` is reported with severity `2`, i.e, it's an Info, not an Error.

The only error in this report is `IO_ERROR` likely caused by not dropping both files (GLB and PNG) to the web-based validator window.

**Comment by malytomas** [comment]
Oh, I thought higher severity is more bad. Thanks for explanation.

**Comment by donmccurdy** [comment]
A bit of extra context — by convention, .glb files are usually self-contained and .gltf files usually have external resources. I would encourage public, user-facing tools to stick to those conventions. But it is not required, and there are rare times you might want to do otherwise.
