### ISSUE TITLE
Validation error for missing bufferView in sparse accessors

### ISSUE THREAD

**Issue by elrnv** [KhronosGroup/glTF-Validator#207]
When validating a GLTF file with a sparse accessor that intentionally omits a bufferView, the spec permits this, however the validator complains:

<img width="666" alt="238094761-100ce15b-dd97-419b-8ce4-cdd787e72bed" src="https://github.com/KhronosGroup/glTF-Validator/assets/1807432/36cb6f1d-2cb0-4cbd-b550-a12082988f0f">

A sample file can be found here: https://github.com/elrnv/gltfgen/raw/master/assets/tet_and_tri_expected.glb

Moved issue from: https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/249

**Comment by lexaknyazev** [comment]
Since there is no buffer view, `byteOffset` must not be defined.
