### ISSUE TITLE
Buffer override should be a warning but not an error

### ISSUE THREAD

**Issue by jimver04** [KhronosGroup/glTF-Validator#210]
Hi, 

why the buffer override is an error ? 

![image](https://github.com/KhronosGroup/glTF-Validator/assets/1898502/5477478e-b0d2-48d2-b23f-53f22e0dffe5)

I have only one bufferView in bufferViews that is used for everything, i.e. for both position attribute and indices. The validator issues an error whereas it should be a warning. The file is correctly displayed in most popular 3d viewers. Are there any performance issues when we use only one bufferView ? I am using Microsoft's GLTF-SDK (@bghgary) for the export. 

![image](https://github.com/KhronosGroup/glTF-Validator/assets/1898502/d3e72ff0-ae93-4c2d-a8f4-b822913c6dac)

![image](https://github.com/KhronosGroup/glTF-Validator/assets/1898502/d4482c9a-1635-4067-9de4-3a744f1cac13)

Thanks in advance for the clarification,
jimver

**Comment by lexaknyazev** [comment]
> one bufferView in bufferViews that is used for everything

This is not allowed ([spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#buffers-and-buffer-views-overview)):
> Buffer views used for images, vertex indices, vertex attributes, or inverse bind matrices MUST contain only one kind of data, i.e., the same buffer view **MUST NOT** be used both for vertex indices and vertex attributes.
