### ISSUE TITLE
Using TEXCOORD_0 or COLOR_0 as morph targets results in MESH_PRIMITIVE_INVALID_ATTRIBUTE error

### ISSUE THREAD

**Issue by UX3D-haertl** [KhronosGroup/glTF-Validator#213]
The spec specifically allows morphing of texcoord and color attributes. [Link](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#morph-targets)
It is also supported by sample viewer.
The description in [mesh.primitive.schema.json](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/mesh.primitive.schema.json) is misleading. I will also raise an issue about it in the glTF repo.

**Comment by stephomi** [comment]
+1 many people are still using the validator.
Made a PR a while ago but it wasn't accepted https://github.com/KhronosGroup/glTF-Validator/pull/193
