### ISSUE TITLE
Validation report format

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Validator#24]
JSON-Schema of validation report hasn't been formally specified yet. 
Can we freeze it? Or should we enhance (or simplify) it in some way?

/cc @pjcozzi @emackey @donmccurdy @zellski @McNopper @sbtron @javagl @AurL

**Comment by pjcozzi** [comment]
Anyone with any validation integration experience have input here?  No strong preference here.

**Comment by emackey** [comment]
The format seems a little odd at the moment.  If I'm not mistaken, there is a root-level object called `errors` that contains multiple arrays of reports, binned by issue class, but also including a reference to the issue class in each report in the bin for that class.

```
errors: {
    "PROBLEM_TYPE_1": [
        // List of problems of type 1, each one specifying that it is type 1.
    ],
    "PROBLEM_TYPE_2": [
        // List of problems of type 2, each one specifying that it is type 2.
    ]
}
```

Should we switch this to be a unified array of reports (not called "errors")?  The receiving app can sort or filter these by type or severity or whatever is needed, so I think just a raw list would be fine.

**Comment by lexaknyazev** [comment]
I don't have any strong opinion here. Existing format tries to semantically answer two common (imo, at least) questions about asset validity:
- Are there any errors? Check that `errors` is undefined or `errors.length == 0`
- Is it possible to easily ignore some particular validation issue (without manual traversing)? Mangle with `errors.IGNORED_TYPE`

Feel free to propose any alternative output format (with sound example). Also, we have `info` object with some stats about asset. Should we keep it (or maybe move into completely separate output)?

**Comment by javagl** [comment]
I don't have a strong preferences either (except for one point, regarding the `info`). I considered to use the validator for automated "integration tests" for JglTF, but this would boil down to the binary "valid or not valid" decision. 

Nevertheless, a specified format might come in handy for some application cases.

The point that emackey mentioned also seemed a bit odd for me at the first glance: The error/warning objects are contained in an array, and the name of this array is the same as the `type`. This seemed to be a redundant redundancy. 

The argument about being able to easily filter out certain warnings sounds reasonable. Whether or not this is a *strong* argument may also depend on the granularity of the warnings. Right now, one can assume that there are not thousands of warnings in one output, so filtering may not be peformance critical

With one caveat: There once was a discussion about warnings for "invalid triangles" (i.e. triangles with duplicate indices), and similar mesh-related warnings. Of course, *this* kind of warning could appear thousands of times in one output. There also was the proposal to combine these into one warning, like *"There are 42134 invalid triangles in the mesh"*, but I don't know the latest state of the discussion/implementation here. 

The greater problem with naming the arrays according to the type might be: It is hard to specify. Right now, the structure is

    "errors": {
        "GLB_UNEXPECTED_END_OF_CHUNK_DATA": [ ... ],
         "INVALID_JSON": [ ... ],
        ....
    }
    "warnings": { ... }

How will these names be specified in the schema? If I'm not mistaken, then **each** of these classes will have to be listed in the `"properties"` of the schema definition, each being *optional*. (For the `type` property, this may be simple: It can be an `enum` with many possible values). When these values are really *property names*, then adding/removing/renaming such properties (or even just moving one of them from the `errors` to the `warnings` or vice versa) may be difficult - but maybe I'm overestimating this, and this is not an issue at all.

---

The point that I *do* have preference about: The `info` object. I think it should not be part of an (initial) spec of the validator output. Of course, it could and should still be part of the output, because it is a very helpful piece of information, e.g. when using the drag-and-drop-validator. But it is, strictly speaking, not part of the validation itself, and it is not clear which information it should contain and how downstream pipelines might use it. To quote and paraphrase Joshua Bloch: *"When in doubt, leave it out"*. It can always be added to the spec later. But when it is there, it can never be taken back.

**Comment by lexaknyazev** [comment]
@alteous @bwasty
Would you like to collaborate on this? I see certain benefits in having standardized validation report format and a common set of test cases.

@javagl 
> ... this would boil down to the binary "valid or not valid" decision.

This is already available in form of exit error code. It is `0` for valid models and `1` otherwise. That's how Travis CI for sample models repo works.

> There also was the proposal to combine these into one warning, like _"There are 42134 invalid triangles in the mesh"_, but I don't know the latest state of the discussion/implementation here.

Implemented about a month ago.

> How will these names be specified in the schema? If I'm not mistaken, ...

It's possible using constrained `additionalProperties` (like `mesh.primitive.attributes` in glTF). I think that validation output schema shouldn't define exact error codes.

>  The `info` object. I think it should not be part of an (initial) spec of the validator output. ...

Are you suggesting to remove it from output for now or just leave unspecified?

**Comment by javagl** [comment]
> Are you suggesting to remove it from output for now or just leave unspecified?

I think it should still be part of the output, but as an unspeficied additional property. 

Specifying it in its current form may cause people to **rely** on its current structure, making future changes more difficult. For example, it currently lists `"hasAnimations": false,`. Even a trivial change, like extending this to `"numAnimations": 42` (which may be helpful, by the way) would require an update of the spec, and to keep the spec clean, the `hasAnimations` property probably should be removed with this change. 

The point is that there are some degrees of freedom for the contents and structure of this `info` object, and unless there already is an agreement on *which* information should be encoded there (and *how*), omitting it in the spec seems like the safer and more considerate choice for me. 

But of course, the final decision is up to you (or the consensus of the working group).

**Comment by javagl** [comment]
Note: *The output itself* could probably also carry version information (about **its** version)

**Comment by emackey** [comment]
The output format could just have a copy of the validator's version number.  I think we're over-complicating things if we start versioning the output independently.

**Comment by emackey** [comment]
Also, with regard to the format of validation messages delivered back to the host app, I'm in favor of a single, flat array.  The objects in the array can each have their own severity level, indication type, etc.

Most applications are going to have to do "something" with each message, possibly transform it or act on it in some way.  A flat array is easiest to sort, organize, categorize in a variety of ways, and of course simple to iterate.

**Comment by lexaknyazev** [comment]
@emackey 
I've got two questions about that:
1. What if an app doesn't care about specific issues and just want a simple answer valid/invalid? When using flat array, it may be reasonable to add top-level property like `"status": "Error|Warning|..."` based on the most severe issue found.
2. What if an app wants to opt-out of some specific validation checks? We can extend API to receive a list of error codes to ignore.

**Comment by emackey** [comment]
Good point, it may be worth having another object at the root with the counts by severity:

```
{
    "count": {
        "error": 2,
        "warning": 1,
        "information": 0,
        "hint": 0
    },
    "messages": [ ...array of 3 messages... ],
    // other info here..
}
```

Or something similar.  Then the app could ask `if (result.count.error > 0)`.

**Comment by emackey** [comment]
And for 2, yes, some folks will almost certainly want to configure the types of messages that are tested for.

**Comment by donmccurdy** [comment]
is there somewhere i can look at the current example output (ideally without setting up the Dart SDK.. 😇)

**Comment by lexaknyazev** [comment]
@donmccurdy
Just drop an asset into online validator.

**Comment by emackey** [comment]
To get everyone on the same page, here's some sample output from a modified (deliberately sabotaged) copy of Box.gltf:

```
[
    {
        "uri": "Busted_Box.gltf",
        "mimeType": "model/gltf+json",
        "errors": {
            "VALUE_NOT_IN_LIST": [
                {
                    "type": "VALUE_NOT_IN_LIST",
                    "path": "#/accessors/1/type",
                    "message": "Invalid value `NotaVEC3`. Valid values are `(SCALAR, VEC2, VEC3, VEC4, MAT2, MAT3, MAT4)`."
                }
            ],
            "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT": [
                {
                    "type": "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT",
                    "path": "#/meshes/0/primitives/0/attributes/NORMAL",
                    "message": "Invalid accessor referenced for this attribute semantic. Valid accessor types are `[{VEC3, FLOAT}]`, got `{null, FLOAT}`."
                }
            ],
            "UNRESOLVED_REFERENCE": [
                {
                    "type": "UNRESOLVED_REFERENCE",
                    "path": "#/nodes/0/children/0",
                    "message": "Unresolved reference: `5`."
                }
            ]
        },
        "warnings": {
            "UNEXPECTED_PROPERTY": [
                {
                    "type": "UNEXPECTED_PROPERTY",
                    "path": "#/scenes/0/testing testing",
                    "message": "Unexpected property."
                }
            ],
            "NODE_EMPTY": [
                {
                    "type": "NODE_EMPTY",
                    "path": "#/nodes/2",
                    "message": "Empty node encountered."
                }
            ]
        },
        "resources": [
            {
                "id": "#/buffers/0",
                "mimeType": "application/octet-stream",
                "byteLength": 648
            }
        ],
        "info": {
            "version": "2.0",
            "generator": "COLLADA2GLTF",
            "hasAnimations": false,
            "hasMaterials": true,
            "hasMorphTargets": false,
            "hasSkins": false,
            "hasTextures": false,
            "hasDefaultScene": true,
            "primitivesCount": 1,
            "maxAttributesUsed": 2
        }
    }
]
```

**Comment by emackey** [comment]
In the above sample, one `VEC3` was changed to `NotaVEC3`, there's a reference to a non-existent node index `5`, there's a property of the default scene called `testing testing`, and there's an empty node in the tree.

**Comment by emackey** [comment]
Sneek peek!

![validatorscreenshot](https://user-images.githubusercontent.com/1235080/31462618-572d3db0-ae9b-11e7-9066-de70fac10010.png)

**Comment by javagl** [comment]
A note about the note obove (which I just scribbled during the call) : The point was **not** to inroduce a dedicated version number for the output. The point was to just add ("any") version number to the output. Depending on how the validator is used, the downstream pipeline might just receive the output and have to cope with it. *Not* providing any version info seems brittle in this regard...

**Comment by emackey** [comment]
Here's a possible way to revise the above output into a single list of messages:

```
{
    "uri": "Busted_Box.gltf",
    "mimeType": "model/gltf+json",
    "validatorVersion": "2.0.0-dev.2",
    "count": {
        "error": 3,
        "warning": 2,
        "info": 0,
        "hint": 0
    },
    "messages": [
        {
            "type": "VALUE_NOT_IN_LIST",
            "severity": "error",
            "path": "#/accessors/1/type",
            "message": "Invalid value `NotaVEC3`. Valid values are `(SCALAR, VEC2, VEC3, VEC4, MAT2, MAT3, MAT4)`."
        },
        {
            "type": "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT",
            "severity": "error",
            "path": "#/meshes/0/primitives/0/attributes/NORMAL",
            "message": "Invalid accessor referenced for this attribute semantic. Valid accessor types are `[{VEC3, FLOAT}]`, got `{null, FLOAT}`."
        },
        {
            "type": "UNRESOLVED_REFERENCE",
            "severity": "error",
            "path": "#/nodes/0/children/0",
            "message": "Unresolved reference: `5`."
        },
        {
            "type": "UNEXPECTED_PROPERTY",
            "severity": "warning",
            "path": "#/scenes/0/testing testing",
            "message": "Unexpected property."
        },
        {
            "type": "NODE_EMPTY",
            "severity": "warning",
            "path": "#/nodes/2",
            "message": "Empty node encountered."
        }
    ],
    "info": {
        "version": "2.0",
        "generator": "COLLADA2GLTF",
        "hasAnimations": false,
        "hasMaterials": true,
        "hasMorphTargets": false,
        "hasSkins": false,
        "hasTextures": false,
        "hasDefaultScene": true,
        "primitivesCount": 1,
        "maxAttributesUsed": 2
    }
}
```

VSCode will need to iterate this list, at the very least to convert the severity enum into a VSCode-specific enum.

**Comment by lexaknyazev** [comment]
To reduce conversion:
- `type` -> `code`
- https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namediagnosticseverityaspan-classcodeitem-id979diagnosticseverityspan
  - `error` -> 0
  - `warning` -> 1

Not a strong opinion, but I'm a bit hesitant about dedicated `count` object (or just just its name).

**Comment by emackey** [comment]
Yeah `count` is probably a conflict or something.  Maybe `totals`?

I'm fine with numeric severity.  It's easier to perform less-than, greater-than comparisons.

**Comment by lexaknyazev** [comment]
WIP:
- added UTC timestamp
- imo, `numTotal.errors` sounds a bit more natural; what do you think? Maybe put totals into `info` object and make it more useful (see @javagl comments above).
```json
{
    "uri": "Busted_Box.gltf",
    "mimeType": "model/gltf+json",
    "validatorVersion": "2.0.0-dev.2",
    "validatedAt": "2017-10-11T20:19:35.224Z",
    "numTotal": {
        "errors": 3,
        "warnings": 2,
        "infos": 0,
        "hints": 0
    },
    "messages": [
        {
            "code": "VALUE_NOT_IN_LIST",
            "severity": 0,
            "path": "#/accessors/1/type",
            "message": "Invalid value `NotaVEC3`. Valid values are `(SCALAR, VEC2, VEC3, VEC4, MAT2, MAT3, MAT4)`."
        },
        {
            "code": "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT",
            "severity": 0,
            "path": "#/meshes/0/primitives/0/attributes/NORMAL",
            "message": "Invalid accessor referenced for this attribute semantic. Valid accessor types are `[{VEC3, FLOAT}]`, got `{null, FLOAT}`."
        },
        {
            "code": "UNRESOLVED_REFERENCE",
            "severity": 0,
            "path": "#/nodes/0/children/0",
            "message": "Unresolved reference: `5`."
        },
        {
            "code": "UNEXPECTED_PROPERTY",
            "severity": 1,
            "path": "#/scenes/0/testing testing",
            "message": "Unexpected property."
        },
        {
            "code": "NODE_EMPTY",
            "severity": 1,
            "path": "#/nodes/2",
            "message": "Empty node encountered."
        }
    ],
    "info": {
        "version": "2.0",
        "generator": "COLLADA2GLTF",
        "hasAnimations": false,
        "hasMaterials": true,
        "hasMorphTargets": false,
        "hasSkins": false,
        "hasTextures": false,
        "hasDefaultScene": true,
        "primitivesCount": 1,
        "maxAttributesUsed": 2
    }
}
```
Also JSON-Pointer syntax is slightly wrong here. It must be percent-encoded when it starts with `#`, or we should drop `#`. Any preference here? See Sections 5 & 6 in [RFC 6901](https://tools.ietf.org/html/rfc6901).

**Comment by donmccurdy** [comment]
What's the distinction between the `resources` and `info.externalResources` sections?

```
        "resources": [
            {
                "id": "#/buffers/0",
                "mimeType": "application/octet-stream"
            },
            {
                "id": "#/images/0"
            }
        ],
        "info": {
            "version": "2.0",
            "generator": "COLLADA2GLTF",
            "externalResources": {
                "buffers": {
                    "#/buffers/0": "Monster0.bin"
                },
                "images": {
                    "#/images/0": "Monster.jpg"
                }
            },
            "hasAnimations": true,
            "hasMaterials": true,
            "hasMorphTargets": false,
            "hasSkins": true,
            "hasTextures": true,
            "hasDefaultScene": true,
            "primitivesCount": 1,
            "maxAttributesUsed": 5
        }
```

at a glance these feel redundant.

EDIT: although i don't see `externalResources` in @emackey's output?

**Comment by lexaknyazev** [comment]
`resources` includes base64 and glb-contained resources with their specific properties (like length for buffers and dimensions for images). `externalResources` lists only external files (without any metadata).

**Comment by emackey** [comment]
> or we should drop `#`. Any preference here?

My preference is drop.  I'm already slicing it off with a `.substring` call anyway.

> Should we remove back-quotes from output?

Yes, I think so.  Markdown-flavored validation messages are not common as far as I know.

**Comment by emackey** [comment]
> Maybe put totals into `info` object

+1

**Comment by lexaknyazev** [comment]
With implementing #27, we could have two flavors of output: complete and interrupted. This may affect format of `info` object (e.g., could we say `"maxAttributesUsed": null` when max number of messages was exceeded before reading atributes?).

Maybe we should have two separate objects: one with validation result (only messages and totals) and other with asset stats and metadata. In case of interrupted validation, the second object may be undefined.

**Comment by lexaknyazev** [comment]
First attempt to address this with formal v6 schema, `info` object is undefined for now:
```json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Validation Report",
    "type": "object",
    "description": "Output of glTF-Validator",
    "properties": {
        "uri": {
            "type": "string",
            "format": "uri-reference",
            "description": "URI of validated asset."
        },
        "mimeType": {
            "description": "MIME type of validated asset.",
            "anyOf": [
                {
                    "const": "model/gltf+json",
                    "description": "glTF asset in plain text form."
                },
                {
                    "const": "model/gltf-binary",
                    "description": "glTF asset in GLB container."
                },
                {
                    "const": null,
                    "description": "Unrecognized file format."
                }
            ]
        },
        "validatorVersion": {
            "type": "string",
            "description": "Version string of glTF-Validator. Must follow semver syntax."
        },
        "validatedAt": {
            "type": "string",
            "format": "date-time",
            "description": "UTC timestamp of validation time."
        },
        "issues": {
            "type": "object",
            "properties": {
                "numErrors": {
                    "type": "integer",
                    "minimum": 0,
                    "default": 0
                },
                "numWarnings": {
                    "type": "integer",
                    "minimum": 0,
                    "default": 0
                },
                "numInfos": {
                    "type": "integer",
                    "minimum": 0,
                    "default": 0
                },
                "numHints": {
                    "type": "integer",
                    "minimum": 0,
                    "default": 0
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "properties": {
                            "code": {
                                "type": "string"
                            },
                            "severity": {
                                "oneOf": [
                                    {
                                        "const": 0,
                                        "description": "Error"
                                    },
                                    {
                                        "const": 1,
                                        "description": "Warning"
                                    },
                                    {
                                        "const": 2,
                                        "description": "Information"
                                    },
                                    {
                                        "const": 3,
                                        "description": "Hint"
                                    }
                                ]
                            },
                            "pointer": {
                                "type": "string",
                                "format": "json-pointer"
                            },
                            "message": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "code",
                            "severity",
                            "pointer",
                            "message"
                        ]
                    }
                }
            }
        },
        "info": {
            "type": "object"
        }
    },
    "required": [
        "uri",
        "mimeType",
        "validatorVersion",
        "validatedAt"
    ]
}
```

**Comment by emackey** [comment]
LGTM.

**Comment by lexaknyazev** [comment]
Updated `info` object, use definitions for common types. Stats about materials/animations/etc isn't there yet. 

Please review.
```json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Validation Report",
    "type": "object",
    "description": "Output of glTF-Validator",
    "definitions": {
        "nonNegativeIntegerDefault0": {
            "type": "integer",
            "minimum": 0,
            "default": 0
        },
        "positiveInteger": {
            "type": "integer",
            "exclusiveMinimum": 0
        }
    },
    "properties": {
        "uri": {
            "type": "string",
            "format": "uri-reference",
            "description": "URI of validated asset."
        },
        "mimeType": {
            "description": "MIME type of validated asset.",
            "anyOf": [
                {
                    "const": "model/gltf+json",
                    "description": "glTF asset in plain text form."
                },
                {
                    "const": "model/gltf-binary",
                    "description": "glTF asset in GLB container."
                },
                {
                    "const": null,
                    "description": "Unrecognized file format."
                }
            ]
        },
        "validatorVersion": {
            "type": "string",
            "description": "Version string of glTF-Validator. Must follow semver syntax."
        },
        "validatedAt": {
            "type": "string",
            "format": "date-time",
            "description": "UTC timestamp of validation time."
        },
        "issues": {
            "type": "object",
            "properties": {
                "numErrors": {
                    "$ref": "#/definitions/nonNegativeIntegerDefault0"
                },
                "numWarnings": {
                    "$ref": "#/definitions/nonNegativeIntegerDefault0"
                },
                "numInfos": {
                    "$ref": "#/definitions/nonNegativeIntegerDefault0"
                },
                "numHints": {
                    "$ref": "#/definitions/nonNegativeIntegerDefault0"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "properties": {
                            "code": {
                                "type": "string"
                            },
                            "severity": {
                                "oneOf": [
                                    {
                                        "const": 0,
                                        "description": "Error"
                                    },
                                    {
                                        "const": 1,
                                        "description": "Warning"
                                    },
                                    {
                                        "const": 2,
                                        "description": "Information"
                                    },
                                    {
                                        "const": 3,
                                        "description": "Hint"
                                    }
                                ]
                            },
                            "pointer": {
                                "type": "string",
                                "format": "json-pointer"
                            },
                            "message": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "code",
                            "severity",
                            "pointer",
                            "message"
                        ]
                    }
                },
                "truncated": {
                    "type": "boolean",
                    "description": "Indicates that validation output is incomplete due to too many messages.",
                    "default": false
                }
            }
        },
        "info": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "description": "The glTF version that this asset targets.",
                    "pattern": "^[0-9]+\\.[0-9]+$"
                },
                "minVersion": {
                    "type": "string",
                    "description": "The minimum glTF version that this asset targets.",
                    "pattern": "^[0-9]+\\.[0-9]+$"
                },
                "generator": {
                    "type": "string",
                    "description": "Tool that generated this glTF model."
                },
                "extensionsUsed": {
                    "type": "array",
                    "description": "Names of glTF extensions used somewhere in this asset.",
                    "items": {
                        "type": "string"
                    },
                    "uniqueItems": true,
                    "minItems": 1
                },
                "extensionsRequired": {
                    "type": "array",
                    "description": "Names of glTF extensions required to properly load this asset.",
                    "items": {
                        "type": "string"
                    },
                    "uniqueItems": true,
                    "minItems": 1
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "pointer": {
                                "type": "string",
                                "format": "json-pointer"
                            },
                            "storage": {
                                "oneOf": [
                                    {
                                        "const": "base64",
                                        "description": "Resource is stored as Base 64 URI."
                                    },
                                    {
                                        "const": "bufferView",
                                        "description": "Resource is stored within glTF buffer and accessed via bufferView."
                                    },
                                    {
                                        "const": "glb",
                                        "description": "Resource is stored in binary chunk of GLB container."
                                    },
                                    {
                                        "const": "external",
                                        "description": "Resource is stored externally."
                                    }
                                ]
                            },
                            "mimeType": {
                                "type": "string"
                            },
                            "byteLength": {
                                "$ref": "#/definitions/positiveInteger"
                            },
                            "image": {
                                "type": "object",
                                "description": "Image-specific metadata.",
                                "properties": {
                                    "width": {
                                        "$ref": "#/definitions/positiveInteger"
                                    },
                                    "height": {
                                        "$ref": "#/definitions/positiveInteger"
                                    },
                                    "format": {
                                        "enum": [
                                            "RGB",
                                            "RGBA",
                                            "LUMINANCE",
                                            "LUMINANCE_ALPHA"
                                        ]
                                    }
                                },
                                "required": [
                                    "width",
                                    "height",
                                    "format"
                                ]
                            }
                        }
                    },
                    "required": [
                        "pointer",
                        "storage",
                        "mimeType",
                        "byteLength"
                    ]
                }
            }
        }
    },
    "required": [
        "uri",
        "mimeType",
        "validatorVersion",
        "validatedAt"
    ]
}
```

**Comment by javagl** [comment]
Looks OK to me from a quick glance. 

But there haven't been any further comments regarding the `info`. Any thoughts here?

(For me, it seems like things like the `info.resources.image.format` or the `byteLength` are rather low-level details. For example: When there is only a link to a PNG, how should the `byteLength` be determined without actually *processing* or at least querying the resource?  I'm not saying that there may not be any use-cases for this, but wonder whether there already *is* the demand for this information...)

**Comment by lexaknyazev** [comment]
> When there is only a link to a PNG, how should the `byteLength` be determined without actually *processing* or at least querying the resource?

Validator queries all external files, gets metadata from actual images.

**Comment by lexaknyazev** [comment]
Such information may be useful for debugging pipeline tools - e.g., checking result of glb/gltf conversion.

**Comment by javagl** [comment]
I see. Just a small remark: I regularly used the drag-and-drop interface to validate **only** a single `gltf` JSON file (not caring about the images). 

(Having to upload 10 MB of PNGs just to check whether some `scene` contains a wrong `node` index would be inconvenient, to say the least).

But this can be (or maybe already *is*) covered by some resilience of the validator at this point. So I assume that it will still be able to validate the actual asset if it can *not* resolve an external reference.

**Comment by lexaknyazev** [comment]
> But this can be (or maybe already *is*) covered by some resilience of the validator at this point. So I assume that it will still be able to validate the actual asset if it can *not* resolve an external reference. 

Fair point. Currently, the validator simply ignores all non-available resources while building `resources` report (i.e., drag-n-drop version checks only glb and base64 resources). The proposal above should be refined a bit to accommodate this. For example, allow `"byteLength": null` for non-available resources.

**Comment by lexaknyazev** [comment]
Live demo of the first implementation of above:
https://lexaknyazev.github.io/glTF-Validator/

If that looks fine, I'll polish code a bit and open a PR.

/cc @emackey @donmccurdy @javagl

**Comment by donmccurdy** [comment]
Looks good to me!

**Comment by emackey** [comment]
> Having to upload 10 MB of PNGs just to check whether some scene contains a wrong node index would be inconvenient, to say the least

The 10 MB don't get uploaded.  Validation is done in JavaScript, in the browser itself.  The drag-and-drop action is just to allow the page to read those local files from disk, but for this app they are not uploaded back to any server.

I'm guessing this is a common misconception.  Maybe a message or something could be added to explain it?

> *NOTE: Validation is performed locally in your browser.  Dropped assets are not uploaded.*

**Comment by lexaknyazev** [comment]
> Maybe a message or something could be added to explain it?

This is already mentioned in readme. We can add similar note to the live page.

**Comment by emackey** [comment]
This is looking really good.

I see the backtics are gone.  Do we still want to wrap user-defined strings in single or double quotes?

```
    Invalid value NotaVEC3. Valid values are (SCALAR, VEC2, VEC3, VEC4, MAT2, MAT3, MAT4).

    Invalid value 'NotaVEC3'. Valid values are ('SCALAR', 'VEC2', 'VEC3', 'VEC4', 'MAT2', 'MAT3', 'MAT4').

    Invalid value "NotaVEC3". Valid values are ("SCALAR", "VEC2", "VEC3", "VEC4", "MAT2", "MAT3", "MAT4").
```

I think numeric values are fine without quotes.

```
    Unresolved reference: 5
```

**Comment by lexaknyazev** [comment]
Lack of quotes may be ambiguous in some cases, while double quotes will look bad in JSON. So, I guess we should wrap strings in single quotes. Numbers are fine without them.
