### ISSUE TITLE
Add API for "max number of returned messages"

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#27]
Would be nice to have a limiting number passed into the API to provide an upper bound on the number of messages returned.  If the app passes in `100` for example, and the validator discovers more than 100 combined errors and warnings, it can halt validation early and return the set it has so far, along with an additional validation message explaining that validation was halted and why.

**Comment by lexaknyazev** [comment]
How should this work when certain checks should be skipped by user's request?

**Comment by emackey** [comment]
The skipped checks don't count against the total.  This is a total number of returned messages, partly to keep the total response size somewhat bounded, and partly to keep the diagnostics UI from being overwhelmed with data.

Currently, following a VSCode sample extension, I already have this limit as a user setting, it just stops reading from the response object after reading *n* number of messages.  But perhaps the validator could optimize this more by keeping the response object smaller, and possibly aborting the validation process itself early.
