### ISSUE TITLE
Validator says "hasAnimations": true when there are textures

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Validator#3]
See https://github.com/KhronosGroup/glTF-Validator/blob/c048336021505b3a1c521e298076d41867770325/lib/src/base/gltf.dart#L327

**Comment by lexaknyazev** [comment]
Good eye, thanks @javagl!
Fixed in https://github.com/KhronosGroup/glTF-Validator/commit/d95fdbee1a7d58571fc151f0d0873810fc3d202f.
