### ISSUE TITLE
doubleToSingle convertion in accessor fromMap

### ISSUE THREAD

**Issue by jox81** [KhronosGroup/glTF-Validator#30]
Hello, 

When trying to extract min value from an accessor, I don't have the same value as the gltf file.

For exemple if the gltf file have the value : 
```
"min" : [ 0.0, 0.0, 0.0, -0.707 ]
```

the extracted value will be converted to 
```
[0.0, 0.0, 0.0, -0.7070000171661377]
```

This is caused by the singlePrecision convertion in the method getFloatList
[https://github.com/KhronosGroup/glTF-Validator/blob/master/lib/src/base/accessor.dart#L164
](url)

Why is that ?

Thanks

**Comment by lexaknyazev** [comment]
Because `-0.707` can't be truly represented with IEEE 754 single-precision floating point type (since `accessor.componentType` is `gl.FLOAT`).

**Comment by jox81** [comment]
Well thank  ! 

I don't understand correctly the math behind so I have to learn more about that.
I just tried to implement gltf/webgl integration with the samples and I did some unit testing about values. 
So It broke but I'll adapt my tests :-)
