### ISSUE TITLE
MESH_PRIMITIVE_INCOMPATIBLE_MODE: args index typo

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Validator#31]
The [message](https://github.com/KhronosGroup/glTF-Validator/blob/55a960559a6b4cf4f9ad0d598443477943b792fc/lib/src/errors.dart#L468-L469) for MESH_PRIMITIVE_INCOMPATIBLE_MODE is

    (args) => 'Number of vertices or indices (`${args[0]}`) '
        'is not compatible with used drawing mode (`${args[0]}`).',

The second `args[0]` should be `args[1]`.

**Comment by lexaknyazev** [comment]
Thanks for report. That typo has been fixed in `2.0.0-dev.1` branch.
