### ISSUE TITLE
Catch explicit "null" values

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#34]
[Broken_Lantern.zip](https://github.com/KhronosGroup/glTF-Validator/files/1447494/Broken_Lantern.zip)

The JSON inside this GLB file contains a snippet that says `"byteOffset":null` instead of `"byteOffset":0` (due to a bug in conversion).

Can the validator be updated to catch this kind of mistake?

**Comment by lexaknyazev** [comment]
This is a known issue (it's mentioned at the end of README). Validator treats `null` values as undefined.

How high priority is this?

**Comment by emackey** [comment]
Not very high.  The major web-based engines handle this gracefully, but the Win10 Mixed Reality Viewer chokes on this value.  I'm about to open a separate PR to get VSCode to stop producing such null values.

**Comment by lexaknyazev** [comment]
Strictly-speaking, this is a schema violation, because `null` is a separate JSON type.

**Comment by lexaknyazev** [comment]
Fixed in 497d71ec64081c37d53e20d8c66a60f154386058.

**Comment by lexaknyazev** [comment]
@emackey 
Consider these two cases:
```json
"bufferViews": [
    {
        "buffer": 0,
        "byteLength": 12,
        "byteOffset": null
    },
    {
        "buffer": 0,
        "byteLength": 12,
        "byteOffset": "null"
    }
]
```

Both bufferViews are invalid with the same error message:
> Type mismatch. Property value 'null' is not a 'integer'.

But `null` isn't the same as `"null"`. Maybe we should write `null` without quotes (as numbers) when it isn't a string?

**Comment by emackey** [comment]
Yes, actual null values may be written without any quotes.
