### ISSUE TITLE
Publishing issues

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#36]
Had some trouble publishing this.  From PowerShell:

```
PS D:\Git\glTF-Validator> pub run grinder npm-publish
grinder running [issues] [npm] [npm-publish]

[issues]
  Total number of issues: 116

[npm]
  E:\Downloads\Dart\dart-sdk\bin\dart2js.bat --no-source-maps --trust-type-annotations --trust-primitives --minify -obuild/npm/gltf_validator.dart.js tool/npm_template\node_wrapper.dart
  Compiled 4,512,080 characters Dart to 324,840 characters JavaScript in 4.99 seconds
  Dart file (tool\npm_template\node_wrapper.dart) compiled to JavaScript: build/npm/gltf_validator.dart.js
  deleting build/npm/gltf_validator.dart.js.deps
  copying package.json to build/npm/
  copying tool/npm_template\index.js to build/npm/
  copying tool/npm_template\README.md to build/npm/
  copying ISSUES.md to build/npm/
  copying LICENSE to build/npm/
  copying 3RD_PARTY to build/npm/
  copying docs\validation.schema.json to build/npm/

[npm-publish]
  npm publish

ProcessException: The system cannot find the file specified.

  Command: npm publish
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:473)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:619)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      run (package:grinder/src/run.dart:29:34)
#4      npmPublish (file:///D:/Git/glTF-Validator/tool/grind.dart:169:7)
```

After this I tried `cd build/npm` and then `npm publish`.  That worked, but published the version number as `2.0.0-dev.1` which I don't think is correct.

https://www.npmjs.com/package/gltf-validator

**Comment by lexaknyazev** [comment]
Version is OK, it matches the one in `pubspec.yaml`. Git tag is a bit different, but it should mean the same. 
I'll look into `npm publish`.

**Comment by lexaknyazev** [comment]
These issues seem to be windows-specific. I'll try to fix them for the next dev-release.

**Comment by emackey** [comment]
Turns out the `npm.cmd` thing wasn't the problem.  The problem was I had manually run the `pub run grinder npm` task, which created the npm folder, and then I ran `pub run grinder npm-publish`, which deleted and wanted to re-create the npm folder immediately.

Windows, for whatever reason, is picky about access to recently-deleted folders.  I don't know if the folder is just queued for deletion, or if some security process is holding onto the deletion-in-progress folder somehow.  But asking it to create a new folder immediately in the old location fails, and when this grinder command fails it leaves the build folder without any npm folder.

This can be reproduced just by running `pub run grinder npm` twice in a row, the second one will fail and the folder will be missing.

**Comment by lexaknyazev** [comment]
> This can be reproduced just by running `pub run grinder npm` twice in a row, the second one will fail and the folder will be missing.

I couldn't reproduce this. Does failure happen here? Could you provide full output?
https://github.com/KhronosGroup/glTF-Validator/blob/7128ee36cc3cc1b3826178efc920089cad8495cf/tool/grind.dart#L140-L143

**Comment by emackey** [comment]
This may just be my own machine or the security software installed.  I'll close this for now since the workaround is quite easy, just delete the old build folder manually before running a build.
