### ISSUE TITLE
Possible false positive?

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#39]
This model came out of Paint 3D and was converted from GLB to glTF by the VSCode extension.

[Bulldozer.zip](https://github.com/KhronosGroup/glTF-Validator/files/1463811/Bulldozer.zip)

The validator reports an error on `mesh_id7` `NORMAL` and `POSITION` saying:

> bufferView.byteStride must be defined when two or more accessors use the same buffer view.

It flags accessors `3` and `5`.  But, those two accessors don't seem to use the same bufferView.

Is the model wrong, or the validator?

**Comment by lexaknyazev** [comment]
The model is wrong (afaik it's a known issue with Paint 3D).
Accessors 2 and 3 use bufferView 1; accessors 4 and 5 use bufferView 2. The validator flags accessors starting with the second for each bufferView. Maybe we could improve messaging there.

**Comment by emackey** [comment]
OK.  I'm fine with closing this unless you think there's a good way to clarify the messaging.
