### ISSUE TITLE
Errors when running in browser.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Validator#40]
Steps to reproduce:

1. Build a test script using validator:

```js
// index.js
const validator = require('gltf-validator');
console.log(validator);
```

2. Compile:

```
browserify index.js -o bundle.js
```

3. Include in webpage:

```html
<!DOCTYPE html>
<script src="bundle.js"></script>
```

4. Error:

```
bundle.js:189 Uncaught ReferenceError: setImmediate is not defined
    at Object.<anonymous> (bundle.js:189)
    at Object.2._process (bundle.js:10039)
    at s (bundle.js:1)
    at bundle.js:1
    at Object.3../gltf_validator.dart.js (bundle.js:10057)
    at s (bundle.js:1)
    at bundle.js:1
    at Object.4.gltf-validator (bundle.js:10094)
    at s (bundle.js:1)
    at e (bundle.js:1)
```

Not sure what assumptions go into Dart's compilation process, but `setImmediate` is a function available to Node.js but [not the browser](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate).

**Comment by lexaknyazev** [comment]
I was able to reproduce this. 
Node environment is a bit different from web browser, so a specific preamble is being added to an npm build. Unfortunately, that preamble is incompatible with web environment.

I'll look into how to fix that.

**Comment by lexaknyazev** [comment]
@donmccurdy Quick fix:
```javascript
// index.js
global.setImmediate = require('timers').setImmediate;
const validator = require('gltf-validator');
console.log(validator);

**Comment by lexaknyazev** [comment]
See #42.

**Comment by donmccurdy** [comment]
Quick test is working now; thanks!
