### ISSUE TITLE
TypeError in Firefox

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Validator#49]
In Firefox v56, before calling any methods on glTF-Validator, I see the following error:

```
TypeError: 'get window' called on an object that does not implement interface Window.
```

Validator is not initialized after that.

Code otherwise working as expected in Chrome and Safari.

**Comment by donmccurdy** [comment]
Demo: https://three-gltf-viewer-fgdilsvzuk.now.sh/

**Comment by lexaknyazev** [comment]
Can confirm in Firefox v57 and MS Edge v40.
