### ISSUE TITLE
Max issues throws exception

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#56]
Just trying this in VSCode, looks like if the validator reaches the `maxIssues` it throws an internal exception now.

**Comment by lexaknyazev** [comment]
Could you give full repro?

**Comment by emackey** [comment]
How do I run unit tests in this repo?  There doesn't seem to be a grind task or README on it.

Can we make a unit test that tests a model with 5 known issues, but sets `maxIssues` to 3?

**Comment by emackey** [comment]
This is my favorite test model to validate, `Busted_Box`.

[Busted_Box.zip](https://github.com/KhronosGroup/glTF-Validator/files/1519258/Busted_Box.zip)

When not capped by `maxIssues`, it should produce 3 errors, 1 warning, and 1 info.

**Comment by lexaknyazev** [comment]
> How do I run unit tests in this repo? 

```
pub run test
```
But this runs only Dart VM tests. JS builds may need additional care for catching possible compiler-related issues.

> Can we make a unit test that tests a model with 5 known issues, but sets `maxIssues` to 3?

Sure, I was waiting for API to stabilize. Will add them soon.

**Comment by lexaknyazev** [comment]
@emackey Should be fixed in `2.0.0-dev.1.6`.
