### ISSUE TITLE
Skins data validation

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Validator#58]
From the offline discussion, all skinning-related checks:
#### Scene Description Issues
- [ ] Joints must have one or more common roots.
- [ ] `skeleton` property, if used, must point to a common root.
- [ ] When a node with a skinned mesh belongs to a scene, the joint tree must be available in the same scene.
- [ ] Local and parent transforms on a node with a skinned mesh are ignored.

#### Data Issues:
- [ ] IBM matrices don't have to be TRS-decomposable.
- [ ] Joint indices must be valid (zeros allowed for zero-weight influences).
- [ ] Linear sum of weights per vertex is `1.0` (across all influences).

**Comment by lexaknyazev** [comment]
Implement https://github.com/KhronosGroup/glTF/pull/1352.

**Comment by donmccurdy** [comment]
> Order of weights when an asset uses more than 4 influences.

From latest discussions, the validator probably does not need to verify order of weights, but should raise a warning or hint when more than 4 influences are used.
