### ISSUE TITLE
"Animation channel cannot target TRS properties of node with defined matrix." Question

### ISSUE THREAD

**Issue by MilosBulat** [KhronosGroup/glTF-Validator#62]
Hi Khronos team,

If glTF file with an animated node is used in glTF previewers that don't support animation that node will be rendered in the default scene position. 
Assuming this limitation was added to optimize glTF file size, is there a design strategy in glTF development for file size and corner cases kinds of tradeoffs?

Thanks,
Miloš

**Comment by lexaknyazev** [comment]
> If glTF file with an animated node is used in glTF previewers that don't support animation that node will be rendered in the default scene position.

Animated node can still have TRS properties defined. The limitation refers only to `node.matrix` property.

**Comment by MilosBulat** [comment]
Hm, that sounds strange. Why is TRS property allowed and matrix property not?

**Comment by lexaknyazev** [comment]
Please see https://github.com/KhronosGroup/glTF/issues/892 and https://github.com/KhronosGroup/glTF/issues/845 for some background on this.

**Comment by MilosBulat** [comment]
Thanks @lexaknyazev that answers my question. :)

Best,
Miloš
