### ISSUE TITLE
Accessor Offset error message wrong?

### ISSUE THREAD

**Issue by webprofusion-chrisc** [KhronosGroup/glTF-Validator#64]
While I'm not great at arithmetic, my calculator is pretty awesome: 7170 / 4 = 1792? Or is that not what this error message means?

` {
                "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
                "message": "Accessor's total byteOffset 7170 isn't a multiple of componentType length 4.",
                "severity": 0,
                "pointer": "/accessors/1/byteOffset"
            },`

**Comment by lexaknyazev** [comment]
Hi Christopher,
my calculator shows that 7170 / 4 = 1792,5.

**Comment by webprofusion-chrisc** [comment]
Lol. I used the windows calculator in programmer mode. Turns our programmers don't do things by halves.
