### ISSUE TITLE
Validation report more than 1,000,000+ issues and my browser cannot open it.

### ISSUE THREAD

**Issue by chipweinberger** [KhronosGroup/glTF-Validator#65]
The size of validation reports has gotten way too large.

The validator reports every single normal that is not normalized for instance.  I'm not sure what else is in the report yet since I cannot open it in my browser.

Instead the validator should say something like "accessor X has non-normalized normals. Found at index 0 (x,x,x), index 1(x,x,x) index 2(x,x,x) and 51,203 other indices."

I imagine there are some other types of checks that need their fat culled in too.

**Comment by lexaknyazev** [comment]
That's on the roadmap, see #29. 
As a temporary workaround, you can mute specific validation issues via config (available in command-line version, npm library, and VS Code plugin). Please let me know if you need any help getting those to work.

**Comment by chipweinberger** [comment]
Awesome =) The validator is an incredible tool.

**Comment by emackey** [comment]
You can also set [options.maxIssues](https://github.com/KhronosGroup/glTF-Validator/blob/f5b364b0ff7a28d5af68e368638026dc88567d08/tool/npm_template/node_wrapper.dart#L191) to halt output before it reaches an unreasonable size.
