### ISSUE TITLE
Incorrect accessor error for morph target weights

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF-Validator#69]
The validator seems to be incorrectly reporting that animation sampler accessors must be unit length for morph target weights.

> Accessor element at index 155 is not of unit length: 0.17094823134817244.

Morph target weights do not need to be unit length. 

Here is an sample model that has this issue:
https://github.com/bghgary/glTF-Sample-Models/tree/add-alien-model/2.0/Alien/glTF

**Comment by lexaknyazev** [comment]
The Alien model shows this error only on accessors with rotation data (`/accessors/70`, `/accessors/72`, `/accessors/74`, `/accessors/76`).

**Comment by bghgary** [comment]
Oh weird. The model I posted is a bit different than the one I have locally. Let me figure what the discrepancy is first.

**Comment by bghgary** [comment]
Sorry, not sure what I was looking at yesterday. You are right that this is rotation data.
