### ISSUE TITLE
Technique parameters with node specified fail validation if they are not FLOAT_MAT4

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/glTF-Validator#7]
For example:
[BoxSemantics.gltf.txt](https://github.com/KhronosGroup/glTF-Validator/files/601054/BoxSemantics.gltf.txt)

`nodeModelInverseTransposeMatrix` is supposed to be `FLOAT_MAT3` because it is `MODELINVERSETRANSPOSE`. I don't think this is expressly forbidden in the spec, but @lexaknyazev, you'd probably know better than I would. 

On the other side of that, there's also `nodeViewportMatrix` which is `VIEWPORT` and a `VEC4`, which I'd say the validator is correct and that shouldn't be allowed.

Edit: I'm also not sure if this is a validator issue or something we shouldn't be doing that needs to be/is already being tightened up in the spec

**Comment by lexaknyazev** [comment]
See https://github.com/KhronosGroup/glTF/issues/563#issuecomment-223122123.

**Comment by lasalvavida** [comment]
Okay, thanks. I will close this and remove the node references on the semantics where it doesn't make sense in the regeneration for BoxSemantics.
