### ISSUE TITLE
Incorrect accessor error for cubic spline rotation tangents

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF-Validator#70]
Here is the model I'm using:
https://github.com/BabylonJS/Babylon.js/blob/master/Playground/scenes/Alien/Alien.gltf

The errors being reported all look like this:
> Accessor element at index 3 is not of unit length: 0.12157953455436363.

These are all quaternion rotations which are tangents of a cubic spline.

**Comment by lexaknyazev** [comment]
@bghgary This issue should be resolved now. [Online version](http://github.khronos.org/glTF-Validator/) updated.

**Comment by lexaknyazev** [comment]
@bghgary This model has non-zero first in-tangents and last out-tangents, while the spec says that they should be zeros because they aren't used. Could you verify?

**Comment by bghgary** [comment]
> This model has non-zero first in-tangents and last out-tangents, while the spec says that they should be zeros because they aren't used.

Yes, I can confirm. I'm just outputting whatever Unity stores. This should be a warning in my opinion as it shouldn't break anything. For the official UnityGLTF repo, we should make sure to zero them out.

**Comment by bghgary** [comment]
Feel free to close. I have verified the fix with the online version.

**Comment by lexaknyazev** [comment]
> This should be a warning in my opinion as it shouldn't break anything.

The reason why I didn't implement it initially is that this check could be quite cumbersome for animated morph weights because the structure of data layout depends on the number of targets and in some theoretically possible edge cases the same output accessor could be used by different meshes.

Nevertheless, I'll put this on the road-map.
