### ISSUE TITLE
How to troubleshoot ACCESSOR_NON_UNIT?

### ISSUE THREAD

**Issue by tkazik** [KhronosGroup/glTF-Validator#72]
Sorry for opening this issue, but I am looking for some advice/help.
I modified an exporter to deal with negative scales and the model looks good now, but during the validation I get tons of errors. All of the type `ACCESSOR_NON_UNIT`:

![errors](https://user-images.githubusercontent.com/15689124/36912006-a9dec398-1e45-11e8-9c90-ceacf7ce461a.png)

I guess I have to have a look at the .bin files. How can I inspect and troubleshoot these? 
Here are the gltf (original and modified):
[models.zip](https://github.com/KhronosGroup/glTF-Validator/files/1776019/models.zip)

Thx a lot!

**Comment by lexaknyazev** [comment]
I'd suggest to modify the exporter to print out lengths of vectors. Other option is to use some importer's or engine's API to get individual values from accessors (assuming that data layout hasn't been broken with scaling modification).

**Comment by tkazik** [comment]
Thank you very much for your hint: Turned out that the normals did not have unit length after the transformation!
