### ISSUE TITLE
Consider including filesize breakdown?

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Validator#73]
I've been wishing I had a tool to show a breakdown for questions like, "why is my file 10mb". For example:

```
walrus.gltf
└── asset ( 50 MB )
    ├── mesh ( 5 meshes, 20 MB total )
    │   ├── position ( 50k vertices, 3 MB )
    │   ├── normal ( 3 MB )
    │   ├── tangent ( 3 MB )
    │   └── morph targets ( 11 MB )
    ├── animation ( 2 clips, 10 MB )
    ├── textures ( 4 images, 20 MB )
    └── other ( 0.15 MB )
```

Do you think this could make sense as part of glTF-Validator, or better to have a separate performance analysis tool?

**Comment by pjcozzi** [comment]
I think gltf-pipeline outputs this.  Way back in the day, I wrote [gltf-statistics](https://github.com/AnalyticalGraphicsInc/gltf-statistics) for this.

As for where it should live, I don't have a strong preference for validator vs. pipeline/toolkit vs. standalone (and perhaps drag & drop).

**Comment by pjcozzi** [comment]
I think I wrote gltf-statistics for glTF 0.8 and instead of updating it to 1.0, we put it in gltf-pipeline since our other tools were already using gltf-pipeline.  I am totally cool if you want to start maintaining gltf-statistics as a micro library, move it to the Khronos GitHub repo, restart it from scratch, etc.

**Comment by lexaknyazev** [comment]
Computing those numbers is an easy task, I think we should make a higher-level decision first.

FWIW, validation report has an `info` section with some loosely-defined fields:
```json
{
  "hasAnimations": true,
  "hasMaterials": true,
  "hasMorphTargets": true,
  "hasSkins": true,
  "hasTextures": true,
  "hasDefaultScene": true,
  "primitivesCount": 8,
  "maxAttributesUsed": 7
}
```

They are not defined in the validation report JSON-Schema, so we can change them at will.

I was thinking about expanding that part into something more useful. Let's say we have a list of all glTF 2.0 features (in addition to the list above; sparse accessors, double-sided materials, multi-UV, etc). It would be interesting to gather their usage data (e.g. send anonymized report from drag-n-drop validation).

The validator can output the stats for further consumption or we can remove that part from it in favor of specialized tools.

**Comment by emackey** [comment]
Wouldn't hurt to have both VSCode and the validator providing this info.  In fact if we play our cards right on the VSCode side, it could even populate its UI tree with size information pulled from the `info` section from the auto-validation of the file being edited (er maybe, assuming we can ship that info from the language server back to the extension client...)

If it adds any noticeable time to the validation run, of course there should be an option to turn it off when not needed.

**Comment by lexaknyazev** [comment]
> populate its UI tree with size information

What kind of report structure would be needed for this? I don't quite understand should it be e.g. primitive-first or buffer-first. The same vertex data could be heavily reused. Ideally, tree outline could show all numbers (e.g. `10 MB, 7 MB shared`).

**Comment by donmccurdy** [comment]
I'm not sure what buffer-first would mean, but primitive-first sounds good. Actually that's more detail than I'd been thinking of, so no complaints, but at a high level I mainly want to know what percentage of my asset is used by Feature A vs Feature B. Where by features, I mean primarily:

- geometry
- keyframe samplers
- morph targets
- textures

But I am wearing a content-author hat on this one, perhaps there are other use cases that a tooling author would choose.

**Comment by najadojo** [comment]
![image](https://user-images.githubusercontent.com/17411617/37312110-037ab34e-2607-11e8-9593-bf972865b4ee.png)
This is what I came up with for gltf-vscode; thoughts? I'll put up the patch shortly.

**Comment by lexaknyazev** [comment]
Where do the numbers come from? Does the VS Code plugin compute them as a part of outline generation?

**Comment by najadojo** [comment]
Yeah the outline generation walks the glTF and calculates these values.

**Comment by donmccurdy** [comment]
Looks wonderful! I don't suppose VS Code makes it possible to right-align the numbers? Would be easier to read/scan that way, but no worries if not.

**Comment by najadojo** [comment]
Unfortunately no. I did attempt that but it just globs all the whitespace together.

**Comment by najadojo** [comment]
The [gltf-vscode pull request](https://github.com/AnalyticalGraphicsInc/gltf-vscode/pull/88) is open.

**Comment by emackey** [comment]
This is published in version 2.1.6.

**Comment by donmccurdy** [comment]
Extension update looks great to me, thanks! 👏

At the risk of being too greedy, it would be nice to _also_ have this feature in glTF-Validator, but I won't complain if you think it's better left elsewhere @lexaknyazev.

**Comment by lexaknyazev** [comment]
What kind of workflow do you expect with this feature available in both places?
Dumping a `pointer->size` map to a validation report may drastically increase JSON size.

**Comment by donmccurdy** [comment]
Size per-pointer isn't necessary, but something like shown at the top of the file. I'd like to put some sort of chart in my viewer showing division of file size between geometry, morph targets, animations, and textures. If not in the validator I will probably just code it into the viewer, but having it in a common place would be more reusable.

**Comment by donmccurdy** [comment]
More recent update, the `gltf-transform inspect model.glb` command also outputs some statistics of this type, in CSV or Markdown form.

Given that options now exist in both gltf-vscode and gltf-transform I'll withdraw the request, but feel free to reopen if it seems appropriate. :)
