### ISSUE TITLE
Add info message for unused texcoords

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#75]
If a model specifies `TEXCOORD_1` or similar on a mesh, but doesn't make use of them in the applied material, can we produce a message?

The `FlightHelmet` model, recently added, [has `TEXCOORD_1` data](https://github.com/KhronosGroup/glTF-Sample-Models/blob/463e270e596b3f03e02165337d9b1b7e877fb185/2.0/FlightHelmet/glTF/FlightHelmet.gltf#L918) but never references it.  Visually the model looks fine, so I don't think this is a warning, just an info message.

**Comment by lexaknyazev** [comment]
This sounds like something very specific. Why perform such check only for texcoord? Virtually every entity could be unused.

**Comment by emackey** [comment]
The more the merrier I suppose.  Earlier today I ran into a problem with some new code that didn't understand TEXCOORD_1 yet, and the FlightHelmet model has it, hence the suggestion.  It's probably not very high priority though.

**Comment by lexaknyazev** [comment]
> The more the merrier

Since the validator already has attribute-specific check for joints/weights, I suppose that texcoord-specific check and error code are fine. For unused JSON objects, we could think of a more generic approach later.

What do you think?

**Comment by lexaknyazev** [comment]
@emackey 
`MESH_PRIMITIVE_UNUSED_TEXCOORD` added to `2.0.0-dev.1.8`.

Btw, `BoxVertexColors` samples have the same issue.
