### ISSUE TITLE
Unrecognized Image Format Should Not Be a Sev 0

### ISSUE THREAD

**Issue by blgrossMS** [KhronosGroup/glTF-Validator#77]
My project generated and uses the MSFT_dds extension as an extensionUsed (https://github.com/sbtron/glTF/tree/MSFT_lod/extensions/Vendor/MSFT_texture_dds). The glTF validator fails this project as sev 0 for:

```
           {
                "code": "VALUE_NOT_IN_LIST",
                "message": "Invalid value 'image/vnd-ms.dds'. Valid values are ('image/jpeg', 'image/png').",
                "severity": 0,
                "pointer": "/images/1/mimeType"
            },
            {
                "code": "UNSATISFIED_DEPENDENCY",
                "message": "Dependency failed. 'mimeType' must be defined.",
                "severity": 0,
                "pointer": "/images/1/bufferView"
            },
            {
                "code": "IMAGE_UNRECOGNIZED_FORMAT",
                "message": "Image format not recognized.",
                "severity": 0,
                "pointer": "/images/1"
            }
```

I think the proper behavior should be:

Image unrecognized format and value not in list should be sev 1 (warning) and there is no unsatisfied dependency error since mimetype is specified.

My two cents are that if an extension is just used and not required, a file that is otherwise compliant should not fail validation.

**Comment by lexaknyazev** [comment]
@blgrossMS Please check updated [online version](http://github.khronos.org/glTF-Validator/). 
Is it worth to issue a new release with just this fix?

**Comment by emackey** [comment]
If no extensions are present, unrecognized image formats should still be severity 0, because the spec only allows certain formats.

**Comment by lexaknyazev** [comment]
How could the validator know whether or not a given extension allows additional image formats? I'm not sure that we should treat all unknown extensions as such.

**Comment by emackey** [comment]
Not sure what the best option is here.  We could allow the validator to recognize MSFT_dds at least in terms of allowing the DDS extension.  I'm just not convinced that reducing the severity globally is the right thing here.

Also, @blgrossMS, the validator does have full configurability here.  You can set your own severity level or disable any particular type of warning in VSCode or in your own toolchain.

**Comment by lexaknyazev** [comment]
We could make some severities depend on the presence of unknown extensions if that helps.

**Comment by lexaknyazev** [comment]
The validation in question checks magic bytes, not file extension. If it recognizes file format (PNG or JPEG), it extracts some metadata from it (dimensions and pixel format). Adding DDS support to it seems to be trivial.

**Comment by emackey** [comment]
Up to you, but, I'm in favor of adding DDS support if that's simple enough, and checking for the presence of the Microsoft DDS extension to suppress the error.

**Comment by blgrossMS** [comment]
Just tested it out and our files now are validated without error. Thank you for adding support.
