### ISSUE TITLE
Accessor min/max array element type does not have to match accessor component type

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Validator#8]
For an accessor that has `int`, `short` or `byte` components, which contains `min`/`max` elements with floating point numbers like

      "max" : [ 3.0 ],
      "min" : [ 0.0 ]

the validator currently emits an error:

            "type": "ARRAY_TYPE_MISMATCH",
            "path": "/accessors/indicesAccessor/min",
            "message": "Type mismatch. Array member `0.0` isn't a `integer`" 

Conceptually, **this makes sense**, of course. 

But according to the spec ( https://github.com/KhronosGroup/glTF/blob/1.0.1/specification/schema/accessor.schema.json#L65 ), the element type is only a `number` (and not necessarily `integer`). 

The `gltf_detailedDescription` and the spec text at https://github.com/KhronosGroup/glTF/tree/1.0.1/specification#accessormax-white_check_mark say something about floating point values, but not about integers. And in fact, I think it's impossible to define the "right" type here in the JSON schema.

Any ideas of how to resolve this? 

(I'd suggest to downgrade this to a "warning", unless the type can be specified more strictly)

**Comment by lexaknyazev** [comment]
Several relevant points here:
- JavaScript has no integers, so JS runtime treats all numbers as doubles (therefore web version of the Validator can't catch that case);
- JSON itself has only "numbers";
- JSON-Schema [encourages](http://json-schema.org/latest/json-schema-core.html#rfc.section.5.3) using integers for integer numbers;
- it should be possible to express value type conditions via JSON-Schema v4's [oneOf](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.24).

With all that said, I'm open to make a separate "integer-stored-as-double" warning issue for this case, however I don't like indices min/max stored as doubles.

**Comment by javagl** [comment]
> I don't like indices min/max stored as doubles.

Sure, I don't like this either. But in most cases, this is not a problem: When the type is fixed, it is declared as `integer`. The special case here arises only from the fact that it will usually be `number`, but may *sometimes* be *required*  to be `integer` (depending on the `componentType`) ...

The type `integer` is *so* prominently used in the spec and schemas that I even thought it was part of JSON itself, but it's indeed specific for the schema, and listed as such in what I considered the reference: https://tools.ietf.org/html/draft-zyp-json-schema-04#section-3.5. 

The document that you referred to is newer, but (and more importantly): It seems to be actively edited, and there are some related issues. Searching a bit reveals this https://github.com/json-schema-org/json-schema-spec/issues/146 (from 13 days ago!), where the first comment says that `1.0` should still be considered as an `integer` (but there is a lot of discussion and links to other issues and PRs that I'd still have to read more thoroughly).

---

Some context: My code generator *does* differentiate between `integer` and `number`, but `integer` is mapped to a Java `int`, and `number` is mapped to a Java `float`. So `min` and `max` are `number` and thus `float[]` arrays. (There may be options for solving this, but I'll tackle this after updating it to process the v04 schemas). I could imagine that this question also affects other libraries/loaders/viewers that are written in *typed* languages (although there are not many that support 1.1 right now).

**Comment by lexaknyazev** [comment]
Afaiu, `"integer"` JSON-Schema type isn't going anywhere, so we can safely continue using it.

---

>  `number` is mapped to a Java `float`

This could be error-prone, because single-precision float can't represent all integers of UINT32 range.
One option is to use `double` everywhere, other is to use generics (or subclasses) with explicit types. The latter could be autogenerated from aforementioned `"oneOf"` feature.

---

As for the whole `1` vs `1.0` issue, I'd prefer following approach:
- writers / converters MUST write `1`;
- readers / loaders SHOULD support both.

**Comment by javagl** [comment]
First, regarding the actual topic:

> writers / converters MUST write 1;

This is reasonable and desirable... 

---

**but...**

it may be more or less difficult for different writers to achieve this. In fact, I just debugstepped through COLLADA2GLTF, where the min/max are stored as `double`, and eventually found that the trailing `.0`'s are *only* omitted "coincidentally", because rapidjson uses `sprintf("%g"...)` for creating the value string internally. Using a different JSON library could mess things up here as well.

Regarding JglTF, it's true that one could translate `number` to `double` by default. It could also be reasonable (even "conceptually cleaner", in some sense) to translate `number` to `java.lang.Number`. But GL usually expects `float` everywhere (e.g. in shaders, as (`float`!) `vec3` uniforms). It would be necessary to convert all these values, manually, and in this regard, both approaches could be clumsy.

One obvious option would be to introduce a special case: By default, translate `number` to `float`, and only for the special case of the accessors min/max, translate it to `Number`. But the current generator was written with the primary goal of getting a simple representation of the glTF classes, and is not (yet) so configurable. Also, I have to admit that it relies heavily on the Jackson JSON (de)serialization mechanisms, and will have to look whether there are options that could be helpful here...

**Comment by lexaknyazev** [comment]
My point on `float` is that using it with uint32 data could result in incorrect values:

**JS**
```javascript
new Float32Array([3000000001])[0] === 3000000000; // true
```
**Java**
```java
(float)3000000001.0 == (float)3000000000.0; // true
```

Throughout glTF, we've got three relevant places:
- `accessor`: 32-bit ints are used only for indices in 1.1, future spec updates will likely enable true integer attributes, so precision of integer min/max could make sense;
- `technique.parameter.value` and `material.values`: 32-bit ints could go to `int` and  `ivec` uniforms.

 Obviously, runtime mustn't corrupt values while transferring them from glTF to GL.

**Comment by javagl** [comment]
Yes, the precision limit will affect integers larger than 2^24. But from a quick search, I think that the places where *actual* `float[]` arrays are used right now in JglTF are safe: Things like `node.matrix`/TRS, or `technique.states.functions.lineWidth`.... Enforcing `double` here would not make any sense. The `technique/material.value` properties are "untyped" anyhow, so these contain `Number` objects where Jackson chose an appropriate implementation (`Double`, by default). 

I think that the `accessors.min/max` are the *only* critical case. I'll probably try to treat this as a special case and use `Number` there. This could also solve the issue of *writing* `1` instead of `1.0` more easily. 

---

(BTW: Strictly speaking, JSON itself does not impose any limit on the numbers *at all*, and one could start arguing about the limit of 2^53 for 64bit integer values when using `double` and when https://www.opengl.org/registry/specs/NV/vertex_attrib_integer_64bit.txt becomes core spec...)
