### ISSUE TITLE
Top-level orphan objects

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Validator#80]
I recently ran into a problem, possibly a bug in an exporter (or an incorrect model), where several `mesh` objects appeared to be duplicates of others, and were not referenced by any nodes.

Could we add checking, maybe for everything except `scene` that objects should be referenced by other objects?  This is not required by the glTF spec, but can indicate wasted data or export issues.  So, it could be an `info` or even a `hint` level message.

**Comment by lexaknyazev** [comment]
@emackey I've almost implemented this feature already, but updating tests will take some more time.

Could we release the current `dev` branch to keep pace?

**Comment by emackey** [comment]
Yes, I'll do some testing of it soon.

**Comment by lexaknyazev** [comment]
In addition to `scene`, top-level `animation` objects should also be excluded from this check.
Only one asset from glTF-Sample-Models fails this new test: `BoxVertexColors` has unused `sampler`.

I can publish a branch (without immediate version update) with this validation implemented, but not sure when all tests could be updated (most of them are failing right now). Are you OK with this?

What do you think of making this check disabled by default (i.e., when `ignoredIssues` is undefined)?
To enable it, a user would need to explicitly pass an empty array there.

/cc @donmccurdy

**Comment by emackey** [comment]
> What do you think of making this check disabled by default

We call out empty nodes with `info` level.  Is there a reason we can't/shouldn't have this enabled by default?  I would be OK even reducing it further to `hint`, the lowest level, if needed.  But conceptually this feels quite similar to empty nodes and unused texcoords.

To get the tests working, I think it's fine for most of the tests to explicitly ignore this one.  The tests are kind of a special case where orphan objects are used all over the place to test things.  Maybe the test harness can even turn this off by default, and only 1 or 2 tests explicitly turn it back on.

Interested to hear from @donmccurdy too.

**Comment by lexaknyazev** [comment]
From my perspective, empty nodes are just empty - they don't contain anything useful spec-wise except names. The spec mentions "library" use-case, so orphaned objects seem to be more "valid". It's implemented as `hint` already.

> Maybe the test harness can even turn this off by default

Yeah, that's my plan.

**Comment by donmccurdy** [comment]
Empty nodes do technically have a purpose, as they might be attachment points for other objects in the application. I think unused materials and meshes are conceptually similar: very likely to be a mistake, but not necessarily so. This seems like appropriate use of `info` or `hint` to me. I lean toward `hint`, and would suggest that all or no `hint` messages should be off by default, rather than turning things off by default on an issue-by-issue basis.

**Comment by lexaknyazev** [comment]
While I totally agree that an application may have some use for empty nodes in a particular asset, I'm having a hard time justifying them in sample models like `BoxVertexColors` (two unused nodes there are clearly an exporter's artifact).

Just for the record, the validator marks a node as unused when it is not referenced by any other object and defines only its own transform (with no children or other attachments including `extras` and `extensions`).

**Comment by donmccurdy** [comment]
> While I totally agree that an application may have some use for empty nodes in a particular asset, I'm having a hard time justifying them in sample models like...

Agreed, although this seems the same as unused top-level objects to me. An application may have some use for them, but in every example so far they have been results of generator error.

**Comment by lexaknyazev** [comment]
Fixed with #83.

**Comment by emackey** [comment]
Hmm.  Just looking at what VSCode does with severity `3` issues, in interactive mode.  It places a tiny squiggle under the open curly brace of an unused object, barely noticeable.  It doesn't add a message to the document problems window at all.  The user really has to hover over the object in question and look carefully to see the message appear as a hover tooltip.

![justasuggestion](https://user-images.githubusercontent.com/1235080/40844762-c6eedaa2-6582-11e8-86ab-5befe5899cc6.png)

I wonder if in the next version we could upgrade `UNUSED_OBJECT` to severity `2`, to match `NODE_EMPTY`?  It feels the same level, subjectively.

Of course I can just fix this on my own machine, by changing my local settings file:

```
    "glTF.Validation.severityOverrides": {
        "UNUSED_OBJECT": 2
    }
```

But I'm starting to think it would be better to upgrade this one a notch for all users.

**Comment by lexaknyazev** [comment]
Is it possible to enable listing hints in problems pane? If not, let's adjust severity on our side.

**Comment by emackey** [comment]
> Is it possible to enable listing hints in problems pane?

I don't think so.  We could change the default settings just for VSCode users, but it's probably better to leave those blank for consistency across the validator's own ecosystem.

**Comment by emackey** [comment]
Severity of this was upgraded in #87.
