### ISSUE TITLE
Inconsistency between npm validator and drag and drop validator for specific models

### ISSUE THREAD

**Issue by ma-tran** [KhronosGroup/glTF-Validator#81]
Hello,

I am running into an inconsistent issue with the NPM gltf-validator and the drag and drop GLTF-validator with specific models.

I downloaded this cube from the khronos model set:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedCube/glTF/AnimatedCube.gltf

Ran it through the drag and drop GTLF validator(http://github.khronos.org/glTF-Validator/), and I got the following results:
```
{
    "uri": "AnimatedCube.gltf",
    "mimeType": "model/gltf+json",
    "validatorVersion": "2.0.0-dev.2.0",
    "validatedAt": "2018-04-05T22:57:00.388Z",
    "issues": {
        "numErrors": 0,
        "numWarnings": 0,
        "numInfos": 0,
        "numHints": 0,
        "messages": [],
        "truncated": false
    },
    "info": {
        "version": "2.0",
        "generator": "VKTS glTF 2.0 exporter",
        "resources": [
            {
                "pointer": "/buffers/0",
                "mimeType": "application/gltf-buffer",
                "storage": "external",
                "uri": "AnimatedCube.bin"
            },
            {
                "pointer": "/images/0",
                "mimeType": null,
                "storage": "external",
                "uri": "AnimatedCube_BaseColor.png"
            },
            {
                "pointer": "/images/1",
                "mimeType": null,
                "storage": "external",
                "uri": "AnimatedCube_MetallicRoughness.png"
            }
        ],
        "hasAnimations": true,
        "hasMaterials": true,
        "hasMorphTargets": false,
        "hasSkins": false,
        "hasTextures": true,
        "hasDefaultScene": true,
        "primitivesCount": 1,
        "maxAttributesUsed": 4
    }
}
```

When I run it through the gltf-validator NPM (https://www.npmjs.com/package/gltf-validator
) with the prescribed "Basic Usage", I get the following:
`Validation failed: NullError: method not found: 'aO' on null`

Try it again with 2CylinderEngine:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/2CylinderEngine/glTF/2CylinderEngine.gltf

Results are the same for both the npm validator and the drag and drop.

Just for clarity, the version used on both the npm validator and the drag and drop is "2.0.0-dev.2.0"

Thanks,

Matt

**Comment by lexaknyazev** [comment]
Hi Matt, thank you for the report.

It's a bug that happens when both conditions are true:
- An asset contains images.
- `externalResourceFunction` isn't provided.

So, everything should be fine with the "Full usage" example.

The fix is ready and will be available asap.

**Comment by ma-tran** [comment]
Thanks!

Matt
