### ISSUE TITLE
Live drag-n-drop down?

### ISSUE THREAD

**Issue by tkazik** [KhronosGroup/glTF-Validator#84]
Live drag-n-drop seems to be down, see: 

http://github.khronos.org/glTF-Validator

Or is the link on the readme not valid anymore:

https://github.com/KhronosGroup/glTF-Validator

Thx!

**Comment by lexaknyazev** [comment]
What do you see there? 
That page is hosted on GitHub and seems to work as usual.

**Comment by tkazik** [comment]
Chrome could not reach the page, other browsers were ok.
But now, it is working again with Chrome...strange.
Anyway thank you for the quick reply, closing this issue.
