### ISSUE TITLE
Does the browser validator say whether the given GLTF model is correct or not?

### ISSUE THREAD

**Issue by ShashankaNataraj** [KhronosGroup/glTF-Validator#88]
I dont see a conclusive "Yes, your model is valid" or "No, your GLTF is malformed" anywhere on screen. Im asked to drop my GLTF file into the browser and it just shows me my GLTF files contents.

**Comment by lexaknyazev** [comment]
In the validation report, there're fields `numErrors`, `numWarnings`, `numInfos`, and `numHints`. If they're zeros, your asset has no issues.

I think we can improve UX there.

**Comment by lexaknyazev** [comment]
Fixed in the latest build, online version updated.
