### ISSUE TITLE
Unknown primitive semantics crash validator

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/glTF-Validator#9]
For example, the glTF:
```JSON
{
  "meshes": {
    "mesh": {
      "primitives": [
        {
          "attributes": {
            "UNKNOWN_SEMANTIC": "accessor"
          }
        }
      ]
    }
  }
}
```

Creates the following error: 

`Uncaught Error: Converting object to an encodable object failed.(…) validator.dart.js:782`

This will also happen if you use `TEXCOORD` instead of `TEXCOORD_#` which is how I discovered this in the first place. This should throw a more verbose error.

**Comment by lexaknyazev** [comment]
Fixed (web build too).

**Comment by lasalvavida** [comment]
Looks good, thanks @lexaknyazev
