### ISSUE TITLE
glTF-Validator zero length Tangents Error 

### ISSUE THREAD

**Issue by bschnurr** [KhronosGroup/glTF-Validator#92]
While converting Fbx file to glTF I came across zero Tangents errors in the validator.
This issue was mentioned  back in nov in issue #33 

I was wondering if there was any updates to whether this will be changed to a warning or not? 

Thank you
Bill

**Comment by lexaknyazev** [comment]
I think, zero-length tangents should be raised and resolved as a spec issue first. Afterward, we'll update the validator if needed.

**Comment by donmccurdy** [comment]
Do we have a spec issue for this?

**Comment by lexaknyazev** [comment]
Closing since the spec issue has been addressed.
