### ISSUE TITLE
Consider warning on duplicate node names.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Validator#93]
While the glTF spec does not require unique names, multiple tools — three.js and Blender, that I'm aware of — require or strongly encourage it. For example, without unique names:

- animation can fail, or be assigned to the wrong nodes, in three.js
- import to Blender _may_ automatically rename duplicate nodes
- or, if names are shared between different types like Bones and Meshes, import to Blender may not rename nodes, in which case export may fail because of similar assumptions

I have not compared in other engines, but I think it would be worthwhile to consider a warning or hint when nodes contain names and those names are duplicated.

**Comment by lexaknyazev** [comment]
Should we check global or per-type uniqueness?

**Comment by emackey** [comment]
For reference, Blender names are unique per-type.  The default scene contains a node named `Cube` that contains a mesh also named `Cube`.  But if you try to add or rename another node or mesh with the same name as an existing one of the same type, you will get `Cube.001`, `Cube.002` etc showing up.

Given the rename behavior, I don't think the Blender Importer will need to do anything special to ensure uniqueness, as Blender seems happy to forcibly apply that at a lower level.  I expect imported models to show up with the `.001` pattern on duplicate names even without our coding it.

**Comment by emackey** [comment]
Conversely, some software may have use for nodes of the same name.  See linked Babylon issue for example.  The spec does specifically call it out as being permitted.  Perhaps software that needs unique names should take on the responsibility for doing that conversion by renaming duplicates, as Blender does.

Sorry I'm a little torn on this one 😅

**Comment by donmccurdy** [comment]
> I don't think the Blender Importer will need to do anything special to ensure uniqueness...

Blender will import mesh/object/bone nodes as different types and not force unique names, but all will be exported as nodes with those names, so there are some exceptions here. I think there is also some caching in the glTF-Blender-Exporter code that relies on unique names.

> Should we check global or per-type uniqueness?

For three.js we only care about having uniquely named nodes. three.js could take on responsibility for renaming these nodes, I'm just worried that other tools will have similar assumptions. three and Blender are just the two I work with most.

**Comment by lexaknyazev** [comment]
I'm having a hard time understanding implications of comments above. What exact rule should we enforce with the validator?

It's super easy to issue a hint on non-unique names in global space. Grouping by type is also feasible but will take a bit more effort.

**Comment by donmccurdy** [comment]
I can't think of a reason a mesh and a material couldn't share a name. I would say either per-type, or only adding the warning to nodes for now, would be best. But we can wait and see how this thread and the babylonjs thread play out.

**Comment by lexaknyazev** [comment]
> only adding the warning to nodes for now

That sounds like a hack to me. Could we at least add a note to the spec? 
I'd wait for more engines' feedback.

**Comment by bghgary** [comment]
> Could we at least add a note to the spec?

I don't have a strong preference whether the validator checks for this or not, but what kind of note would we add to the spec? It already says this:

> These property values are not guaranteed to be unique as they are intended to contain values created when the asset was authored.

**Comment by lexaknyazev** [comment]
> what kind of note would we add to the spec?

That's my problem with this proposal. The spec explicitly says that names don't have to be unique, so a validation warning would be in conflict with the spec as it is now. Updated language could say something specific about _node names_ (if that's the case). Otherwise, it's engines/importers issue that has nothing to do with assets being valid.

**Comment by emackey** [comment]
Yeah, I feel like we already committed to non-unique names with that note in the existing spec.  Importers have to deal with that now, and there are a couple ways to do that including renaming or using index values instead.

**Comment by donmccurdy** [comment]
Unity similarly expects unique names, and [UnityGLTF alters assets when loading](https://github.com/KhronosGroup/UnityGLTF/blob/dc61bbdada77f34f3efd1e0650426365e077ee53/UnityGLTF/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs#L133-L135) to accommodate this. It [looks](https://forums.unrealengine.com/development-discussion/c-gameplay-programming/31205-why-would-you-name-objects) [likely](https://api.unrealengine.com/INT/API/Runtime/CoreUObject/UObject/MakeUniqueObjectName/index.html) that Unreal wants the same.

We'll switch to overwriting user-specified names in three.js too, probably. I don't think arbitrary renaming is necessarily good for users either, so using unique names still seems like a best practice. In general I don't think hints about best practices are out of scope for the validator, but not a strong preference in this particular case.
