### ISSUE TITLE
Unsupported extension: KHR_techniques_webgl

### ISSUE THREAD

**Issue by tkazik** [KhronosGroup/glTF-Validator#95]
Hi folks

Recently I converted some models from gltf v1.0 to v2.0 using the [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline).  The pipeline uses 
[KHR_techniques_webgl](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_techniques_webgl), which currently create a warning in the validation, see:

![validator](https://user-images.githubusercontent.com/15689124/44307906-40ff2c00-a3ab-11e8-8dc9-7164091530a2.png)

Will you adapt that, once the following is merged?

https://github.com/AnalyticalGraphicsInc/cesium/pull/6805

Btw, any ideas, what causes the other info-level issues?

The model can be found here: 
[CesiumBalloon.zip](https://github.com/KhronosGroup/glTF-Validator/files/2300238/CesiumBalloon.zip)

Thx a lot!

**Comment by lexaknyazev** [comment]
Support for WebGL extension will be added soon. Info-level messages are related to it because UVs and textures are used only by WebGL techniques in this asset.

**Comment by tkazik** [comment]
Sounds good!
Also looking forward to the integration of the following two extensions:

- KHR_lights
- KHR_draco_mesh_compression

Thank you!

**Comment by donmccurdy** [comment]
I think it's too soon to support the draft `KHR_techniques_webgl`, it's unclear whether the extension will be ratified in its current form, or at all.

There is no `KHR_lights`, perhaps you mean `KHR_lights_punctual`?

**Comment by lexaknyazev** [comment]
The `KHR_techniques_webgl` extension has been in draft for over a year. I don't think it'll change.

/cc @pjcozzi

**Comment by donmccurdy** [comment]
I'm afraid the lack of changes in the past year indicates a lack of momentum, more than a state of completion. I'm not sure it should be ratified as a KHR-prefixed extension.

**Comment by pjcozzi** [comment]
I believe there are some users of `KHR_techniques_webgl` in the Cesium ecosystem, e.g., for shaders for polylines, but I don't anticipate a ton of growth here and I don't think the Cesium team will have bandwidth any time soon to bring this extension out of draft so I don't know that it is a priority for the validator right now.

**Comment by emackey** [comment]
The current [plan is to deprecate KHR_techniques_webgl](https://github.com/KhronosGroup/glTF/pull/1852#issuecomment-692781738).
