### ISSUE TITLE
dart dependency check failure

### ISSUE THREAD

**Issue by boblaublaw** [KhronosGroup/glTF-Validator#96]
Having some trouble with the dependency resolution for dart.

I have version 2.1.0-dev.2.0 yet `pub get` fails, complaining that I require version 2.0.0-dev.68.0.

Isn't 2.1.0-dev.2.0 higher than 2.0.0-dev.68.0?  Apologies if I'm misunderstanding something obvious.

```
[joe@prolepsis glTF-Validator(master) $]$ pub --version
Pub 2.1.0-dev.2.0
[joe@prolepsis glTF-Validator(master) $]$ dart --version
Dart VM version: 2.1.0-dev.2.0 (Wed Aug 22 20:11:29 2018 +0200) on "macos_x64"
[joe@prolepsis glTF-Validator(master) $]$ pub get
Resolving dependencies...
The current Dart SDK version is 2.1.0-dev.2.0.

Because gltf requires SDK version >=2.0.0-dev.68.0 <2.0.0, version solving failed.
```

**Comment by lexaknyazev** [comment]
The latest tagged release was before stable 2.0 SDK, so this is expected (hence `<2.0.0`). I'll update it in a few hours.

**Comment by boblaublaw** [comment]
Thanks, in the meantime I dug into the `pubspec.yaml` and sorted myself out.

**Comment by lexaknyazev** [comment]
New release has been tagged.
