### ISSUE TITLE
"NullError: method not found: 'buffer' on null" when validating glTF

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF-Validator#99]
Repro:
1. Take this model [SittingBox.zip](https://github.com/KhronosGroup/glTF-Validator/files/2471111/SittingBox.zip) and put it on the glTF-Validator web page.

This original repro is trying to validate a glb in the BabylonJS sandbox that came from here: https://github.com/mrdoob/three.js/blob/master/examples/models/gltf/SittingBox.glb. The zip file with the glTF file was extracted from the glb without modification.

If I set `validateAccessorData` to false, then it doesn't repro.

**Comment by lexaknyazev** [comment]
I've fixed crash internally, will open a PR with a couple more updates following recent discussions.

Btw, this asset shows a new corner case. A non-GLB file which doesn't have `buffer.uri` defined. Spec doesn't seem to address this one.
